/*
 * Copyright (c) 2024, Gnosis Research Center, Illinois Institute of Technology
 * All rights reserved.
 *
 * This file is part of IOWarp Core.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * SYCL twin of work_orchestrator_gpu.cc.
 *
 * Submits a persistent single_task kernel that runs WorkerSycl::PollOnce()
 * in a loop until the host writes control->exit_flag = 1. The structure
 * mirrors the CUDA orchestrator with three differences:
 *   1. Single-source SYCL: the persistent kernel is a lambda passed to
 *      sycl::handler::single_task — no separate __global__ entry point.
 *   2. No CUDA Dynamic Parallelism: tasks execute inline within the
 *      persistent kernel (see worker_sycl.h).
 *   3. The "stream" hosted in WorkOrchestrator::stream_ is a heap
 *      sycl::queue allocated by GpuApi::CreateStream(). The opaque
 *      void* representation matches the CUDA path so the host-facing
 *      WorkOrchestrator API is identical.
 */

#if HSHM_ENABLE_SYCL

#include "chimaera/ipc_manager.h"
#include "chimaera/gpu/work_orchestrator.h"
#include "chimaera/gpu/container.h"
#include "chimaera/gpu/pool_manager.h"
#include "chimaera/gpu/worker_sycl.h"
#include "chimaera/config_manager.h"
#include "hermes_shm/util/gpu_api.h"
#include "hermes_shm/util/gpu_intrinsics.h"

#include <sycl/sycl.hpp>

// Autogenerated per-chimod GPU module registry. Same header consumed by
// the CUDA orchestrator; under HSHM_ENABLE_SYCL it emits a SYCL-flavoured
// AllocGpuContainerHost that placement-news the right GpuRuntime subclass.
#include "autogen/gpu_work_orchestrator_modules.h"

namespace chi {

namespace {

/** Opaque kernel names. Each SYCL submission needs a distinct type. */
class chimaera_orchestrator_sycl_launch_kernel;
class chimaera_orchestrator_sycl_resume_kernel;
class chimaera_init_queue_sycl_kernel;

}  // namespace

//==============================================================================
// gpu::WorkOrchestrator out-of-class method implementations (SYCL backend)
//==============================================================================

bool gpu::WorkOrchestrator::Launch(const IpcManagerGpuInfo &gpu_info, u32 blocks,
                                    u32 threads_per_block,
                                    char *cpu2gpu_queue_base) {
  if (is_launched_) {
    return true;
  }

  // Pinned-host control structure: allocated as SYCL host USM so the
  // persistent kernel can read exit_flag and write running_flag without
  // explicit memcpy.
  auto *pinned_control = hshm::GpuApi::MallocHost<gpu::WorkOrchestratorControl>(
      sizeof(gpu::WorkOrchestratorControl));
  control_ = pinned_control;
  if (!control_) {
    HLOG(kError,
         "gpu::WorkOrchestrator (SYCL): MallocHost for control failed");
    return false;
  }
  std::memset(static_cast<void *>(control_), 0,
              sizeof(gpu::WorkOrchestratorControl));
  control_->cpu2gpu_queue_base = cpu2gpu_queue_base;

  // Device PoolManager — same layout as the CUDA path.
  auto *d_pm =
      hshm::GpuApi::Malloc<gpu::PoolManager>(sizeof(gpu::PoolManager));
  if (!d_pm) {
    HLOG(kError,
         "gpu::WorkOrchestrator (SYCL): Malloc for PoolManager failed");
    hshm::GpuApi::FreeHost(control_);
    control_ = nullptr;
    return false;
  }
  d_pool_mgr_ = d_pm;

  // Zero-initialize the device PoolManager via host->device copy.
  gpu::PoolManager host_pm;
  hshm::GpuApi::Memcpy(d_pm, &host_pm, sizeof(gpu::PoolManager));

  // Dedicated stream so the persistent kernel doesn't block other queues.
  stream_ = hshm::GpuApi::CreateStream();
  if (!stream_) {
    HLOG(kError, "gpu::WorkOrchestrator (SYCL): CreateStream failed");
    hshm::GpuApi::Free(d_pool_mgr_);
    hshm::GpuApi::FreeHost(control_);
    d_pool_mgr_ = nullptr;
    control_ = nullptr;
    return false;
  }

  // Saved launch parameters (orchestrator runs as 1-WI single_task; kept
  // for Pause/Resume parity with the CUDA path).
  blocks_ = blocks;
  threads_per_block_ = threads_per_block;

  // Stage the launch parameters in pinned host USM. SYCL forbids capturing
  // non-trivially-copyable types (IpcManagerGpuInfo holds a MemoryBackend)
  // by value in a kernel lambda — checked by sycl::is_device_copyable_v<T>.
  // Allocating in host USM lets the kernel read individual fields by
  // pointer without triggering the device-copyable check.
  auto *gpu_info_storage =
      hshm::GpuApi::MallocHost<IpcManagerGpuInfo>(sizeof(IpcManagerGpuInfo));
  if (!gpu_info_storage) {
    HLOG(kError,
         "gpu::WorkOrchestrator (SYCL): MallocHost for gpu_info failed");
    hshm::GpuApi::DestroyStream(stream_);
    hshm::GpuApi::Free(d_pool_mgr_);
    hshm::GpuApi::FreeHost(control_);
    stream_ = nullptr;
    d_pool_mgr_ = nullptr;
    control_ = nullptr;
    return false;
  }
  std::memcpy(static_cast<void *>(gpu_info_storage), &gpu_info,
              sizeof(IpcManagerGpuInfo));
  gpu_info_storage->gpu2gpu_num_lanes = 1;
  gpu_info_storage->internal_num_lanes = 1;
  // Stash on the orchestrator object so Finalize/Resume can free it.
  gpu_info_storage_ = gpu_info_storage;

  // Phase 10: allocate the IpcManager itself in host USM so the persistent
  // kernel can capture its pointer and bind it as g_ipc_manager_ptr via
  // CHIMAERA_GPU_ORCHESTRATOR_INIT. The IpcManager has a trivial default
  // ctor (POD-ish: a few pointer / bool members), so placement-init via
  // memset+constructor works.
  auto *ipc_storage =
      hshm::GpuApi::MallocHost<gpu::IpcManager>(sizeof(gpu::IpcManager));
  if (!ipc_storage) {
    HLOG(kError,
         "gpu::WorkOrchestrator (SYCL): MallocHost for IpcManager failed");
    hshm::GpuApi::FreeHost(gpu_info_storage);
    hshm::GpuApi::DestroyStream(stream_);
    hshm::GpuApi::Free(d_pool_mgr_);
    hshm::GpuApi::FreeHost(control_);
    gpu_info_storage_ = nullptr;
    stream_ = nullptr;
    d_pool_mgr_ = nullptr;
    control_ = nullptr;
    return false;
  }
  new (ipc_storage) gpu::IpcManager();
  ipc_storage_ = ipc_storage;

  auto *control_ptr = control_;
  auto *pm_ptr = d_pm;
  auto *ipc_ptr = ipc_storage;
  auto *q = static_cast<sycl::queue *>(stream_);

  HLOG(kInfo,
       "Launching GPU work orchestrator (SYCL single_task, inline dispatch)");

  q->submit([&](sycl::handler &cgh) {
    cgh.single_task<chimaera_orchestrator_sycl_launch_kernel>([=]() {
      // Bind the captured IpcManager pointer as g_ipc_manager_ptr so any
      // chimod method called via the dispatch table (worker.PollOnce ->
      // container->Run -> RunImpl -> chimod method) can use CHI_IPC.
      CHIMAERA_GPU_ORCHESTRATOR_INIT(*gpu_info_storage, /*num_blocks=*/1,
                                      ipc_ptr);

      gpu::WorkerSycl worker;
      worker.Init(0,
                  gpu_info_storage->cpu2gpu_queue,
                  gpu_info_storage->gpu2gpu_queue,
                  gpu_info_storage->internal_queue,
                  pm_ptr,
                  control_ptr->cpu2gpu_queue_base,
                  control_ptr);
      worker.gpu_info_ptr_ = gpu_info_storage;
      worker.ipc_mgr_ = ipc_ptr;

      control_ptr->running_flag = 1;
      HSHM_DEVICE_FENCE_SYSTEM();

      while (worker.is_running_ && !control_ptr->exit_flag) {
        worker.PollGpu2Gpu();
        worker.PollCpu2Gpu();
      }

      worker.FlushProfile();
      worker.Finalize();
      (void)g_ipc_manager;  // silence unused-reference warnings
    });
  });

  launched_num_warps_ = 1;
  is_launched_ = true;
  HLOG(kInfo, "GPU work orchestrator launched (SYCL)");
  return true;
}

void gpu::WorkOrchestrator::Finalize() {
  if (!is_launched_) {
    return;
  }

  if (control_) {
    control_->exit_flag = 1;
  }

  if (stream_) {
    hshm::GpuApi::Synchronize(stream_);
    hshm::GpuApi::DestroyStream(stream_);
    stream_ = nullptr;
  } else {
    hshm::GpuApi::Synchronize();
  }

  if (d_pool_mgr_) {
    hshm::GpuApi::Free(d_pool_mgr_);
    d_pool_mgr_ = nullptr;
  }
  if (control_) {
    hshm::GpuApi::FreeHost(control_);
    control_ = nullptr;
  }
  if (gpu_info_storage_) {
    hshm::GpuApi::FreeHost(gpu_info_storage_);
    gpu_info_storage_ = nullptr;
  }
  if (ipc_storage_) {
    ipc_storage_->~IpcManager();
    hshm::GpuApi::FreeHost(ipc_storage_);
    ipc_storage_ = nullptr;
  }

  is_launched_ = false;
  HLOG(kInfo, "GPU work orchestrator finalized (SYCL)");
}

void gpu::WorkOrchestrator::Pause() {
  if (!is_launched_) {
    return;
  }
  control_->exit_flag = 1;
  HLOG(kInfo, "GPU work orchestrator (SYCL): exit_flag set, waiting...");
  hshm::GpuApi::Synchronize(stream_);
  HLOG(kInfo, "GPU work orchestrator (SYCL): kernel synchronized");
  is_launched_ = false;
}

void gpu::WorkOrchestrator::PrepareResume() {
  // No cross-warp scratch resources under SYCL inline-dispatch; no-op.
}

void gpu::WorkOrchestrator::Resume(const IpcManagerGpuInfo &gpu_info) {
  if (is_launched_) {
    return;
  }

  control_->exit_flag = 0;
  control_->running_flag = 0;

  // Reuse the host-USM gpu_info_storage_ from Launch(); refresh contents
  // with the caller's resume parameters before re-submitting the kernel.
  if (!gpu_info_storage_) {
    HLOG(kError,
         "gpu::WorkOrchestrator (SYCL): Resume called without prior Launch");
    return;
  }
  std::memcpy(static_cast<void *>(gpu_info_storage_), &gpu_info,
              sizeof(IpcManagerGpuInfo));
  gpu_info_storage_->gpu2gpu_num_lanes = 1;
  gpu_info_storage_->internal_num_lanes = 1;

  auto *control_ptr = control_;
  auto *pm_ptr = static_cast<gpu::PoolManager *>(d_pool_mgr_);
  auto *q = static_cast<sycl::queue *>(stream_);
  auto *info_ptr = gpu_info_storage_;
  auto *ipc_ptr = ipc_storage_;

  q->submit([&](sycl::handler &cgh) {
    cgh.single_task<chimaera_orchestrator_sycl_resume_kernel>([=]() {
      CHIMAERA_GPU_ORCHESTRATOR_INIT(*info_ptr, /*num_blocks=*/1, ipc_ptr);

      gpu::WorkerSycl worker;
      worker.Init(0,
                  info_ptr->cpu2gpu_queue,
                  info_ptr->gpu2gpu_queue,
                  info_ptr->internal_queue,
                  pm_ptr,
                  control_ptr->cpu2gpu_queue_base,
                  control_ptr);
      worker.gpu_info_ptr_ = info_ptr;
      worker.ipc_mgr_ = ipc_ptr;

      control_ptr->running_flag = 1;
      HSHM_DEVICE_FENCE_SYSTEM();

      while (worker.is_running_ && !control_ptr->exit_flag) {
        worker.PollGpu2Gpu();
        worker.PollCpu2Gpu();
      }

      worker.FlushProfile();
      worker.Finalize();
      (void)g_ipc_manager;
    });
  });

  is_launched_ = true;
  HLOG(kInfo, "GPU work orchestrator resumed (SYCL)");
}

void gpu::WorkOrchestrator::RegisterGpuContainer(const PoolId &pool_id,
                                                  void *gpu_container_ptr) {
  if (!d_pool_mgr_ || !gpu_container_ptr) {
    return;
  }

  auto *d_pm = static_cast<gpu::PoolManager *>(d_pool_mgr_);
  gpu::PoolManager host_pm;
  hshm::GpuApi::Memcpy(&host_pm, d_pm, sizeof(gpu::PoolManager));
  host_pm.RegisterContainer(pool_id,
                             static_cast<gpu::Container *>(gpu_container_ptr));
  hshm::GpuApi::Memcpy(d_pm, &host_pm, sizeof(gpu::PoolManager));

  HLOG(kInfo, "Registered GPU container for pool {} (SYCL)", pool_id);
}

void *gpu::WorkOrchestrator::AllocGpuContainer(const PoolId &pool_id,
                                                u32 container_id,
                                                const std::string &chimod_name) {
  // Phase 6 autogen now emits a SYCL branch in AllocGpuContainerHost that
  // placement-news the right GpuRuntime subclass on a USM region sized via
  // GetGpuModuleSize(). This call dispatches there.
  return gpu::AllocGpuContainerHost(pool_id, container_id,
                                    chimod_name.c_str());
}

//==============================================================================
// InitQueueOnDevice — one-shot kernel to construct allocator + GpuTaskQueue
//==============================================================================

hipc::FullPtr<GpuTaskQueue> gpu::InitQueueOnDevice(char *device_data,
                                                  size_t capacity,
                                                  u32 num_lanes,
                                                  u32 queue_depth) {
  // Output offset lives in shared USM so the host can read it back without
  // a separate device->host memcpy.
  size_t *out_off =
      sycl::malloc_shared<size_t>(1, hshm::GpuApi::SyclQueue());
  if (!out_off) {
    HLOG(kError, "InitQueueOnDevice (SYCL): malloc_shared failed");
    return hipc::FullPtr<GpuTaskQueue>::GetNull();
  }
  *out_off = static_cast<size_t>(-1);

  // Dedicated queue so we don't synchronize against any persistent
  // orchestrator kernel that might already be running.
  sycl::queue init_q(sycl::gpu_selector_v);

  init_q.submit([&](sycl::handler &cgh) {
    cgh.single_task<chimaera_init_queue_sycl_kernel>([=]() {
      hipc::MemoryBackend proxy;
      proxy.data_ = device_data;
      proxy.data_capacity_ = capacity;

      CHI_QUEUE_ALLOC_T *alloc = proxy.MakeAlloc<CHI_QUEUE_ALLOC_T>();
      if (!alloc) {
        *out_off = static_cast<size_t>(-1);
        return;
      }

      hipc::FullPtr<GpuTaskQueue> q = alloc->template NewObj<GpuTaskQueue>(
          alloc, num_lanes, 2, queue_depth);
      *out_off = q.IsNull() ? static_cast<size_t>(-1) : q.shm_.off_.load();
    });
  });
  init_q.wait_and_throw();

  size_t off = *out_off;
  sycl::free(out_off, hshm::GpuApi::SyclQueue());

  if (off == static_cast<size_t>(-1)) {
    return hipc::FullPtr<GpuTaskQueue>::GetNull();
  }

  hipc::FullPtr<GpuTaskQueue> result;
  result.shm_.off_ = off;
  result.shm_.alloc_id_ = hipc::AllocatorId(0, 0);
  result.ptr_ = reinterpret_cast<GpuTaskQueue *>(device_data + off);
  return result;
}

}  // namespace chi

#endif  // HSHM_ENABLE_SYCL
