// Auto-generated GPU lib_exec for bdev
// Include inside GpuRuntime class body
// This file is autogenerated - do not edit manually.

template <typename ArchiveT>
HSHM_GPU_FUN void LoadTaskTmpl(
    chi::u32 method, ArchiveT &archive,
    const hipc::FullPtr<chi::Task> &task) {
  switch (method) {
    case Method::kAllocateBlocks: {
      auto typed = task.template Cast<AllocateBlocksTask>();
      if (archive.GetMsgType() == chi::LocalMsgType::kSerializeIn)
        typed->SerializeIn(archive);
      else
        typed->SerializeOut(archive);
      break;
    }
    case Method::kFreeBlocks: {
      auto typed = task.template Cast<FreeBlocksTask>();
      if (archive.GetMsgType() == chi::LocalMsgType::kSerializeIn)
        typed->SerializeIn(archive);
      else
        typed->SerializeOut(archive);
      break;
    }
    case Method::kWrite: {
      auto typed = task.template Cast<WriteTask>();
      if (archive.GetMsgType() == chi::LocalMsgType::kSerializeIn)
        typed->SerializeIn(archive);
      else
        typed->SerializeOut(archive);
      break;
    }
    case Method::kRead: {
      auto typed = task.template Cast<ReadTask>();
      if (archive.GetMsgType() == chi::LocalMsgType::kSerializeIn)
        typed->SerializeIn(archive);
      else
        typed->SerializeOut(archive);
      break;
    }
    case Method::kUpdate: {
      auto typed = task.template Cast<UpdateTask>();
      if (archive.GetMsgType() == chi::LocalMsgType::kSerializeIn)
        typed->SerializeIn(archive);
      else
        typed->SerializeOut(archive);
      break;
    }
    default: break;
  }
}

template <typename ArchiveT>
HSHM_GPU_FUN void SaveTaskTmpl(
    chi::u32 method, ArchiveT &archive,
    const hipc::FullPtr<chi::Task> &task) {
  switch (method) {
    case Method::kAllocateBlocks:
      task.template Cast<AllocateBlocksTask>()->SerializeOut(archive);
      break;
    case Method::kFreeBlocks:
      task.template Cast<FreeBlocksTask>()->SerializeOut(archive);
      break;
    case Method::kWrite:
      task.template Cast<WriteTask>()->SerializeOut(archive);
      break;
    case Method::kRead:
      task.template Cast<ReadTask>()->SerializeOut(archive);
      break;
    case Method::kUpdate:
      task.template Cast<UpdateTask>()->SerializeOut(archive);
      break;
    default: break;
  }
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN void RunImpl(
    chi::gpu::Container *self_, chi::u32 method,
    hipc::FullPtr<chi::Task> task_ptr, chi::gpu::RunContext &rctx) {
  auto *self = static_cast<GpuRuntime *>(self_);
  switch (method) {
    case Method::kAllocateBlocks:
      self->AllocateBlocks(task_ptr.template Cast<AllocateBlocksTask>(), rctx);
      break;
    case Method::kFreeBlocks:
      self->FreeBlocks(task_ptr.template Cast<FreeBlocksTask>(), rctx);
      break;
    case Method::kWrite:
      self->Write(task_ptr.template Cast<WriteTask>(), rctx);
      break;
    case Method::kRead:
      self->Read(task_ptr.template Cast<ReadTask>(), rctx);
      break;
    case Method::kUpdate:
      self->Update(task_ptr.template Cast<UpdateTask>(), rctx);
      break;
    default: break;
  }
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN hipc::FullPtr<chi::Task> AllocTaskImpl(
    chi::gpu::Container *self_, chi::u32 method) {
  // Phase 10: bind g_ipc_manager_ptr so CHI_IPC under SYCL resolves
  // to the kernel-scope IpcManager (set by the worker via
  // container->ipc_mgr_ before dispatch).
  [[maybe_unused]] auto *g_ipc_manager_ptr = self_->ipc_mgr_;
  (void)self_;
  switch (method) {
    case Method::kAllocateBlocks: {
      auto _tp = CHI_IPC->NewTaskBase<AllocateBlocksTask>(0); return _tp.template Cast<chi::Task>();
    }
    case Method::kFreeBlocks: {
      auto _tp = CHI_IPC->NewTaskBase<FreeBlocksTask>(0); return _tp.template Cast<chi::Task>();
    }
    case Method::kWrite: {
      auto _tp = CHI_IPC->NewTaskBase<WriteTask>(0); return _tp.template Cast<chi::Task>();
    }
    case Method::kRead: {
      auto _tp = CHI_IPC->NewTaskBase<ReadTask>(0); return _tp.template Cast<chi::Task>();
    }
    case Method::kUpdate: {
      auto _tp = CHI_IPC->NewTaskBase<UpdateTask>(0); return _tp.template Cast<chi::Task>();
    }
    default: return hipc::FullPtr<chi::Task>::GetNull();
  }
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN hipc::FullPtr<chi::Task> AllocLoadTaskDefaultImpl(
    chi::gpu::Container *self_, chi::u32 method, chi::GpuLoadTaskArchive &ar) {
  auto *self = static_cast<GpuRuntime *>(self_);
  auto task_ptr = self->alloc_task_(self_, method);
  if (task_ptr.IsNull()) return task_ptr;
  ar.SetMsgType(chi::LocalMsgType::kSerializeIn);
  self->LoadTaskTmpl(method, ar, task_ptr);
  return task_ptr;
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN hipc::FullPtr<chi::Task> AllocLoadDeserImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::GpuLoadTaskArchive &ar) {
  auto *self = static_cast<GpuRuntime *>(self_);
  auto task_ptr = AllocTaskImpl(self_, method);
  if (!task_ptr.IsNull()) {
    ar.SetMsgType(chi::LocalMsgType::kSerializeIn);
    self->LoadTaskTmpl(method, ar, task_ptr);
  }
  return task_ptr;
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN void LoadTaskDefaultImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::GpuLoadTaskArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  ar.SetMsgType(chi::LocalMsgType::kSerializeIn);
  static_cast<GpuRuntime *>(self_)->LoadTaskTmpl(method, ar, task);
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN void SaveTaskDefaultImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::GpuSaveTaskArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  static_cast<GpuRuntime *>(self_)->SaveTaskTmpl(method, ar, task);
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN void LoadTaskOutputImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::GpuLoadTaskArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  ar.SetMsgType(chi::LocalMsgType::kSerializeOut);
  static_cast<GpuRuntime *>(self_)->LoadTaskTmpl(method, ar, task);
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN void DestroyTaskImpl(
    chi::gpu::Container *self_, chi::u32 method,
    hipc::FullPtr<chi::Task> &task) {
  if (task.IsNull()) return;
  switch (method) {
    case Method::kAllocateBlocks:
      task.template Cast<AllocateBlocksTask>().ptr_->~AllocateBlocksTask();
      break;
    case Method::kFreeBlocks:
      task.template Cast<FreeBlocksTask>().ptr_->~FreeBlocksTask();
      break;
    case Method::kWrite:
      task.template Cast<WriteTask>().ptr_->~WriteTask();
      break;
    case Method::kRead:
      task.template Cast<ReadTask>().ptr_->~ReadTask();
      break;
    case Method::kUpdate:
      task.template Cast<UpdateTask>().ptr_->~UpdateTask();
      break;
    default: task.ptr_->~Task(); break;
  }
}

/** Fix up SSO/SVO pointers after cudaMemcpy for CPU→GPU POD tasks */
HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN void FixupTaskImpl(
    chi::gpu::Container *self_, chi::u32 method,
    hipc::FullPtr<chi::Task> task) {
  (void)self_;
  switch (method) {
    case Method::kAllocateBlocks:
      task.template Cast<AllocateBlocksTask>().ptr_->FixupAfterCopy();
      break;
    case Method::kWrite:
      task.template Cast<WriteTask>().ptr_->FixupAfterCopy();
      break;
    case Method::kRead:
      task.template Cast<ReadTask>().ptr_->FixupAfterCopy();
      break;
    case Method::kFreeBlocks:
      task.template Cast<FreeBlocksTask>().ptr_->FixupAfterCopy();
      break;
    default: break;
  }
}

HSHM_GPU_FUN GpuRuntime() {
  run_ = &RunImpl;
  fixup_task_ = &FixupTaskImpl;
  alloc_task_ = &AllocTaskImpl;
  alloc_load_deser_ = &AllocLoadDeserImpl;
  alloc_load_task_ = &AllocLoadTaskDefaultImpl;
  load_task_ = &LoadTaskDefaultImpl;
  save_task_ = &SaveTaskDefaultImpl;
  load_task_output_ = &LoadTaskOutputImpl;
  destroy_task_ = &DestroyTaskImpl;
}
