/**
 * Auto-generated execution implementation for core ChiMod
 * Implements Container virtual APIs (Run, SaveTask, LoadTask, NewCopyTask, NewTask)
 * using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "clio_cae/core/core_runtime.h"
#include "clio_cae/core/autogen/core_methods.h"
#include <clio_runtime/clio_runtime.h>
#include <clio_runtime/task.h>  // For TaskResume coroutine return type

namespace clio::cae::core {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Init(const clio::run::PoolId &pool_id, const std::string &pool_name,
                   clio::run::u32 container_id) {
  // Call base class initialization
  clio::run::Container::Init(pool_id, pool_name, container_id);

  // Initialize the client for this ChiMod
  client_ = Client(pool_id);

  // Initialize per-method load prediction model
  DefineModel(Method::kMaxMethodId);
  SetMethodNames(Method::GetMethodNames());
}

clio::run::TaskResume Runtime::Run(clio::run::u32 method, clio::run::shared_ptr<clio::run::Task> task_ptr) {
  CLIO_TASK_BODY_BEGIN
  switch (method) {
    case Method::kCreate: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      CLIO_CO_AWAIT(Create(typed_task));
      break;
    }
    case Method::kDestroy: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      CLIO_CO_AWAIT(Destroy(typed_task));
      break;
    }
    case Method::kMonitor: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      CLIO_CO_AWAIT(Monitor(typed_task));
      break;
    }
    case Method::kParseOmni: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<ParseOmniTask>();
      CLIO_CO_AWAIT(ParseOmni(typed_task));
      break;
    }
    case Method::kProcessHdf5Dataset: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<ProcessHdf5DatasetTask>();
      CLIO_CO_AWAIT(ProcessHdf5Dataset(typed_task));
      break;
    }
    case Method::kExportData: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<ExportDataTask>();
      CLIO_CO_AWAIT(ExportData(typed_task));
      break;
    }
    case Method::kPutBlob: {
      auto& typed_task = task_ptr.template Cast<PutBlobTask>();
      CLIO_CO_AWAIT(PutBlob(typed_task));
      break;
    }
    case Method::kGetBlob: {
      auto& typed_task = task_ptr.template Cast<GetBlobTask>();
      CLIO_CO_AWAIT(GetBlob(typed_task));
      break;
    }
    case Method::kGetOrCreateTag: {
      auto& typed_task = task_ptr.template Cast<GetOrCreateTagTask>();
      CLIO_CO_AWAIT(GetOrCreateTag(typed_task));
      break;
    }
    case Method::kSemanticSearch: {
      auto& typed_task = task_ptr.template Cast<SemanticSearchTask>();
      CLIO_CO_AWAIT(SemanticSearch(typed_task));
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
  CLIO_CO_RETURN;
  CLIO_TASK_BODY_END
}

void Runtime::SaveTask(clio::run::u32 method, clio::run::SaveTaskArchive& archive, 
                        clio::run::shared_ptr<clio::run::Task>& task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      archive << *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      archive << *typed_task;
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      archive << *typed_task;
      break;
    }
    case Method::kParseOmni: {
      auto& typed_task = task_ptr.template Cast<ParseOmniTask>();
      archive << *typed_task;
      break;
    }
    case Method::kProcessHdf5Dataset: {
      auto& typed_task = task_ptr.template Cast<ProcessHdf5DatasetTask>();
      archive << *typed_task;
      break;
    }
    case Method::kExportData: {
      auto& typed_task = task_ptr.template Cast<ExportDataTask>();
      archive << *typed_task;
      break;
    }
    case Method::kPutBlob: {
      auto& typed_task = task_ptr.template Cast<PutBlobTask>();
      archive << *typed_task;
      break;
    }
    case Method::kGetBlob: {
      auto& typed_task = task_ptr.template Cast<GetBlobTask>();
      archive << *typed_task;
      break;
    }
    case Method::kGetOrCreateTag: {
      auto& typed_task = task_ptr.template Cast<GetOrCreateTagTask>();
      archive << *typed_task;
      break;
    }
    case Method::kSemanticSearch: {
      auto& typed_task = task_ptr.template Cast<SemanticSearchTask>();
      archive << *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadTask(clio::run::u32 method, clio::run::LoadTaskArchive& archive,
                        clio::run::shared_ptr<clio::run::Task>& task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kParseOmni: {
      auto& typed_task = task_ptr.template Cast<ParseOmniTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kProcessHdf5Dataset: {
      auto& typed_task = task_ptr.template Cast<ProcessHdf5DatasetTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kExportData: {
      auto& typed_task = task_ptr.template Cast<ExportDataTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kPutBlob: {
      auto& typed_task = task_ptr.template Cast<PutBlobTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kGetBlob: {
      auto& typed_task = task_ptr.template Cast<GetBlobTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kGetOrCreateTag: {
      auto& typed_task = task_ptr.template Cast<GetOrCreateTagTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kSemanticSearch: {
      auto& typed_task = task_ptr.template Cast<SemanticSearchTask>();
      archive >> *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

clio::run::shared_ptr<clio::run::Task> Runtime::AllocLoadTask(clio::run::u32 method, clio::run::LoadTaskArchive& archive) {
  clio::run::shared_ptr<clio::run::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalLoadTask(clio::run::u32 method, clio::run::DefaultLoadArchive& archive,
                            clio::run::shared_ptr<clio::run::Task>& task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kParseOmni: {
      auto& typed_task = task_ptr.template Cast<ParseOmniTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kProcessHdf5Dataset: {
      auto& typed_task = task_ptr.template Cast<ProcessHdf5DatasetTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kExportData: {
      auto& typed_task = task_ptr.template Cast<ExportDataTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kPutBlob: {
      auto& typed_task = task_ptr.template Cast<PutBlobTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kGetBlob: {
      auto& typed_task = task_ptr.template Cast<GetBlobTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kGetOrCreateTag: {
      auto& typed_task = task_ptr.template Cast<GetOrCreateTagTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kSemanticSearch: {
      auto& typed_task = task_ptr.template Cast<SemanticSearchTask>();
      archive >> *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

clio::run::shared_ptr<clio::run::Task> Runtime::LocalAllocLoadTask(clio::run::u32 method, clio::run::DefaultLoadArchive& archive) {
  clio::run::shared_ptr<clio::run::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LocalLoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalSaveTask(clio::run::u32 method, clio::run::DefaultSaveArchive& archive, 
                             clio::run::shared_ptr<clio::run::Task>& task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kParseOmni: {
      auto& typed_task = task_ptr.template Cast<ParseOmniTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kProcessHdf5Dataset: {
      auto& typed_task = task_ptr.template Cast<ProcessHdf5DatasetTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kExportData: {
      auto& typed_task = task_ptr.template Cast<ExportDataTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kPutBlob: {
      auto& typed_task = task_ptr.template Cast<PutBlobTask>();
      archive << *typed_task;
      break;
    }
    case Method::kGetBlob: {
      auto& typed_task = task_ptr.template Cast<GetBlobTask>();
      archive << *typed_task;
      break;
    }
    case Method::kGetOrCreateTag: {
      auto& typed_task = task_ptr.template Cast<GetOrCreateTagTask>();
      archive << *typed_task;
      break;
    }
    case Method::kSemanticSearch: {
      auto& typed_task = task_ptr.template Cast<SemanticSearchTask>();
      archive << *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

clio::run::shared_ptr<clio::run::Task> Runtime::NewCopyTask(clio::run::u32 method, clio::run::shared_ptr<clio::run::Task>& orig_task_ptr, bool deep) {
  auto* ipc_manager = CLIO_IPC;
  if (!ipc_manager) {
    return clio::run::shared_ptr<clio::run::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<CreateTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<CreateTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kDestroy: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<DestroyTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<DestroyTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kMonitor: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<MonitorTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<MonitorTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kParseOmni: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ParseOmniTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<ParseOmniTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<ParseOmniTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kProcessHdf5Dataset: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ProcessHdf5DatasetTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<ProcessHdf5DatasetTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<ProcessHdf5DatasetTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kExportData: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ExportDataTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<ExportDataTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<ExportDataTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kPutBlob: {
      auto new_task_ptr = ipc_manager->NewTask<PutBlobTask>();
      if (!new_task_ptr.IsNull()) {
        auto& task_typed = orig_task_ptr.template Cast<PutBlobTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<PutBlobTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kGetBlob: {
      auto new_task_ptr = ipc_manager->NewTask<GetBlobTask>();
      if (!new_task_ptr.IsNull()) {
        auto& task_typed = orig_task_ptr.template Cast<GetBlobTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<GetBlobTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kGetOrCreateTag: {
      auto new_task_ptr = ipc_manager->NewTask<GetOrCreateTagTask>();
      if (!new_task_ptr.IsNull()) {
        auto& task_typed = orig_task_ptr.template Cast<GetOrCreateTagTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<GetOrCreateTagTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kSemanticSearch: {
      auto new_task_ptr = ipc_manager->NewTask<SemanticSearchTask>();
      if (!new_task_ptr.IsNull()) {
        auto& task_typed = orig_task_ptr.template Cast<SemanticSearchTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<SemanticSearchTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    default: {
      // For unknown methods, create base Task copy
      auto new_task_ptr = ipc_manager->NewTask<clio::run::Task>();
      if (!new_task_ptr.IsNull()) {
        new_task_ptr->Copy(ctp::ipc::FullPtr<clio::run::Task>(orig_task_ptr.get()));
        return new_task_ptr;
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
  return clio::run::shared_ptr<clio::run::Task>();
}

clio::run::shared_ptr<clio::run::Task> Runtime::NewTask(clio::run::u32 method) {
  auto* ipc_manager = CLIO_IPC;
  if (!ipc_manager) {
    return clio::run::shared_ptr<clio::run::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kDestroy: {
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kMonitor: {
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kParseOmni: {
      auto new_task_ptr = ipc_manager->NewTask<ParseOmniTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kProcessHdf5Dataset: {
      auto new_task_ptr = ipc_manager->NewTask<ProcessHdf5DatasetTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kExportData: {
      auto new_task_ptr = ipc_manager->NewTask<ExportDataTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kPutBlob: {
      auto new_task_ptr = ipc_manager->NewTask<PutBlobTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kGetBlob: {
      auto new_task_ptr = ipc_manager->NewTask<GetBlobTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kGetOrCreateTag: {
      auto new_task_ptr = ipc_manager->NewTask<GetOrCreateTagTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kSemanticSearch: {
      auto new_task_ptr = ipc_manager->NewTask<SemanticSearchTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    default: {
      // For unknown methods, return null pointer
      return clio::run::shared_ptr<clio::run::Task>();
    }
  }
}

void Runtime::AggregateOut(clio::run::u32 method, clio::run::shared_ptr<clio::run::Task>& orig_task,
                        const clio::run::shared_ptr<clio::run::Task>& replica_task) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = orig_task.template Cast<CreateTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = orig_task.template Cast<DestroyTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = orig_task.template Cast<MonitorTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kParseOmni: {
      auto& typed_task = orig_task.template Cast<ParseOmniTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kProcessHdf5Dataset: {
      auto& typed_task = orig_task.template Cast<ProcessHdf5DatasetTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kExportData: {
      auto& typed_task = orig_task.template Cast<ExportDataTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kPutBlob: {
      auto& typed_task = orig_task.template Cast<PutBlobTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kGetBlob: {
      auto& typed_task = orig_task.template Cast<GetBlobTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kGetOrCreateTag: {
      auto& typed_task = orig_task.template Cast<GetOrCreateTagTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kSemanticSearch: {
      auto& typed_task = orig_task.template Cast<SemanticSearchTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    default: {
      orig_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
  }
}


} // namespace clio::cae::core
