/*
 * Copyright (c) 2024, Gnosis Research Center, Illinois Institute of Technology
 * All rights reserved.
 *
 * This file is part of IOWarp Core.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * chimaera repo refresh - ChiMod Autogeneration Utility
 *
 * This utility automatically generates libexec source files (.cc) and methods
 * header files (.h) for ChiMods based on their chimaera_mod.yaml configuration files.
 *
 * The libexec source files implement Container virtual API methods (Run, Del,
 * SaveTask, LoadTask, AllocLoadTask, LocalLoadTask, LocalAllocLoadTask,
 * NewCopy, Aggregate) with switch-case dispatch.
 *
 * Usage:
 *     chimaera repo refresh <chimod_repo_path>
 */

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

#include <yaml-cpp/yaml.h>
#include <hermes_shm/util/logging.h>

#include "chimaera_commands.h"

namespace fs = std::filesystem;

/**
 * Structure to hold method information
 */
struct Method {
  std::string constant_name;
  std::string method_name;
  int method_id;
  bool is_inherited;
};

/**
 * ChiMod Generator class
 * Handles generation of autogenerated files for ChiMods
 */
class ChiModGenerator {
 private:
  fs::path repo_path_;
  fs::path repo_yaml_path_;
  std::string repo_namespace_;

 public:
  explicit ChiModGenerator(const std::string& repo_path)
      : repo_path_(fs::absolute(repo_path)),
        repo_yaml_path_(repo_path_ / "chimaera_repo.yaml") {
    if (!fs::exists(repo_yaml_path_)) {
      throw std::runtime_error("Repository YAML not found: " + repo_yaml_path_.string());
    }

    // Load repository namespace from chimaera_repo.yaml
    YAML::Node repo_config = LoadRepoConfig();
    repo_namespace_ = repo_config["namespace"] ? repo_config["namespace"].as<std::string>() : "chimaera";
  }

  /**
   * Load the repository configuration
   */
  YAML::Node LoadRepoConfig() {
    try {
      return YAML::LoadFile(repo_yaml_path_.string());
    } catch (const YAML::Exception& e) {
      throw std::runtime_error("Failed to parse repository YAML: " + std::string(e.what()));
    }
  }

  /**
   * Load a specific ChiMod configuration
   */
  YAML::Node LoadChiModConfig(const std::string& chimod_name) {
    fs::path chimod_yaml_path = repo_path_ / chimod_name / "chimaera_mod.yaml";
    if (!fs::exists(chimod_yaml_path)) {
      throw std::runtime_error("ChiMod YAML not found: " + chimod_yaml_path.string());
    }

    try {
      return YAML::LoadFile(chimod_yaml_path.string());
    } catch (const YAML::Exception& e) {
      throw std::runtime_error("Failed to parse ChiMod YAML: " + std::string(e.what()));
    }
  }

  /**
   * Extract methods from configuration, filtering out those with value -1
   */
  std::vector<Method> GetMethods(const YAML::Node& config) {
    std::vector<Method> methods;

    // Process all key-value pairs in the config
    for (auto it = config.begin(); it != config.end(); ++it) {
      std::string key = it->first.as<std::string>();

      // Skip non-method keys
      if (key.length() == 0 || key[0] != 'k' || !it->second.IsScalar()) {
        continue;
      }

      // Try to parse as integer
      int value;
      try {
        value = it->second.as<int>();
      } catch (const YAML::Exception&) {
        continue; // Skip non-integer values
      }

      // Skip unimplemented methods (value -1)
      if (value == -1) {
        continue;
      }

      // Skip lifecycle-only methods that don't have task types
      // These are handled separately in GenerateLibExecSource
      if (key == "kRestart") {
        continue;
      }

      std::string method_name = key.substr(1); // Remove the 'k' prefix
      Method method;
      method.constant_name = key;
      method.method_name = method_name;
      method.method_id = value;
      method.is_inherited = value < 10;  // Inherited methods have IDs < 10
      methods.push_back(method);
    }

    // Sort by method ID
    std::sort(methods.begin(), methods.end(),
              [](const Method& a, const Method& b) {
                return a.method_id < b.method_id;
              });

    return methods;
  }

  /**
   * Generate the methods header file
   */
  std::string GenerateMethodsHeader(const std::string& chimod_name, const YAML::Node& config,
                                     const std::string& repo_namespace) {
    auto methods = GetMethods(config);
    std::string namespace_name = repo_namespace;
    std::string module_name = config["module_name"] ? config["module_name"].as<std::string>() : chimod_name;

    std::ostringstream oss;
    std::string chimod_upper;
    std::transform(chimod_name.begin(), chimod_name.end(), std::back_inserter(chimod_upper),
                   [](unsigned char c) { return std::toupper(c); });

    // Build namespace_upper for unique include guard
    std::string namespace_upper;
    std::transform(namespace_name.begin(), namespace_name.end(), std::back_inserter(namespace_upper),
                   [](unsigned char c) {
                     if (c == ':') return '_';
                     return (char)std::toupper(c);
                   });

    // Build the header content with unique include guard using namespace
    oss << "#ifndef " << namespace_upper << "_" << chimod_upper << "_AUTOGEN_METHODS_H_\n";
    oss << "#define " << namespace_upper << "_" << chimod_upper << "_AUTOGEN_METHODS_H_\n";
    oss << "\n";
    oss << "#include <chimaera/chimaera.h>\n";
    oss << "#include <string>\n";
    oss << "#include <vector>\n";
    oss << "\n";
    oss << "/**\n";
    oss << " * Auto-generated method definitions for " << module_name << "\n";
    oss << " */\n";
    oss << "\n";
    oss << "namespace " << namespace_name << "::" << chimod_name << " {\n";
    oss << "\n";
    oss << "namespace Method {\n";

    // Add inherited methods
    std::vector<Method> inherited_methods;
    std::copy_if(methods.begin(), methods.end(), std::back_inserter(inherited_methods),
                 [](const Method& m) { return m.is_inherited; });

    if (!inherited_methods.empty()) {
      oss << "// Inherited methods\n";
      for (const auto& method : inherited_methods) {
        oss << "GLOBAL_CROSS_CONST chi::u32 " << method.constant_name << " = " << method.method_id << ";\n";
      }
      oss << "\n";
    }

    // Add custom methods
    std::vector<Method> custom_methods;
    std::copy_if(methods.begin(), methods.end(), std::back_inserter(custom_methods),
                 [](const Method& m) { return !m.is_inherited; });

    if (!custom_methods.empty()) {
      oss << "// " << module_name << "-specific methods\n";
      for (const auto& method : custom_methods) {
        oss << "GLOBAL_CROSS_CONST chi::u32 " << method.constant_name << " = " << method.method_id << ";\n";
      }
    }

    // Emit kMaxMethodId (one past the highest method ID)
    if (!methods.empty()) {
      oss << "\nGLOBAL_CROSS_CONST chi::u32 kMaxMethodId = " << (methods.back().method_id + 1) << ";\n";
    } else {
      oss << "\nGLOBAL_CROSS_CONST chi::u32 kMaxMethodId = 0;\n";
    }

    // Emit GetMethodNames() function returning names indexed by method ID
    oss << "\ninline const std::vector<std::string>& GetMethodNames() {\n";
    oss << "  static const std::vector<std::string> names = [] {\n";
    oss << "    std::vector<std::string> v(kMaxMethodId);\n";
    for (const auto& method : methods) {
      oss << "    v[" << method.method_id << "] = \"" << method.method_name << "\";\n";
    }
    oss << "    return v;\n";
    oss << "  }();\n";
    oss << "  return names;\n";
    oss << "}\n";

    oss << "}  // namespace Method\n";
    oss << "\n";
    oss << "}  // namespace " << namespace_name << "::" << chimod_name << "\n";
    oss << "\n";
    oss << "#endif  // " << chimod_upper << "_AUTOGEN_METHODS_H_\n";

    return oss.str();
  }

  /**
   * Get the task type name for a method
   */
  std::string GetTaskTypeName(const std::string& method_name, const std::string& chimod_name) {
    // Special cases for common inherited methods
    if (method_name == "Create") {
      return "CreateTask";
    } else if (method_name == "Destroy") {
      return "DestroyTask";
    } else if (method_name.length() >= 11 && method_name.substr(0, 11) == "GetOrCreate") {
      // Template-based task
      return chimod_name + "::" + method_name + "Task<" + chimod_name + "::CreateParams>";
    }

    // Regular task (default case)
    return method_name + "Task";
  }

  /**
   * Generate the lib_exec source file (.cc) with Container virtual API implementations
   */
  std::string GenerateLibExecSource(const std::string& chimod_name, const YAML::Node& config,
                                     const std::string& repo_namespace) {
    auto methods = GetMethods(config);
    std::string namespace_name = repo_namespace;
    std::string module_name = config["module_name"] ? config["module_name"].as<std::string>() : chimod_name;

    std::ostringstream oss;

    // Build the source content
    oss << "/**\n";
    oss << " * Auto-generated execution implementation for " << module_name << " ChiMod\n";
    oss << " * Implements Container virtual APIs (Run, SaveTask, LoadTask, NewCopyTask, NewTask)\n";
    oss << " * using switch-case dispatch\n";
    oss << " * \n";
    oss << " * This file is autogenerated - do not edit manually.\n";
    oss << " * Changes should be made to the autogen tool or the YAML configuration.\n";
    oss << " */\n";
    oss << "\n";
    oss << "#include \"" << namespace_name << "/" << module_name << "/" << chimod_name << "_runtime.h\"\n";
    oss << "#include \"" << namespace_name << "/" << module_name << "/autogen/" << chimod_name << "_methods.h\"\n";
    oss << "#include <chimaera/chimaera.h>\n";
    oss << "#include <chimaera/task.h>  // For TaskResume coroutine return type\n";
    oss << "\n";
    oss << "namespace " << namespace_name << "::" << chimod_name << " {\n";
    oss << "\n";
    oss << "//==============================================================================\n";
    oss << "// Container Virtual API Implementations\n";
    oss << "//==============================================================================\n";
    oss << "\n";
    oss << "void Runtime::Init(const chi::PoolId &pool_id, const std::string &pool_name,\n";
    oss << "                   chi::u32 container_id) {\n";
    oss << "  // Call base class initialization\n";
    oss << "  chi::Container::Init(pool_id, pool_name, container_id);\n";
    oss << "\n";
    oss << "  // Initialize the client for this ChiMod\n";
    oss << "  client_ = Client(pool_id);\n";
    oss << "\n";
    oss << "  // Initialize per-method load prediction model\n";
    oss << "  DefineModel(Method::kMaxMethodId);\n";
    oss << "  SetMethodNames(Method::GetMethodNames());\n";
    oss << "}\n";
    oss << "\n";

    // Generate Restart if kRestart is defined in the YAML with a non-negative value
    if (config["kRestart"] && config["kRestart"].as<int>(-1) >= 0) {
      oss << "void Runtime::Restart(const chi::PoolId &pool_id, const std::string &pool_name,\n";
      oss << "                      chi::u32 container_id) {\n";
      oss << "  is_restart_ = true;\n";
      oss << "  Init(pool_id, pool_name, container_id);\n";
      oss << "}\n";
      oss << "\n";
    }

    oss << "chi::TaskResume Runtime::Run(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {\n";
    oss << "  switch (method) {\n";

    // Add Run switch cases for each method
    // All method calls use co_await since Run is a coroutine and methods
    // may return TaskResume (coroutines). Methods returning void are wrapped
    // to be awaitable. This ensures coroutines actually execute rather than
    // being discarded when the return value is ignored.
    for (const auto& method : methods) {
      std::string task_type = GetTaskTypeName(method.method_name, chimod_name);
      oss << "    case Method::" << method.constant_name << ": {\n";
      oss << "      // Cast task FullPtr to specific type\n";
      oss << "      hipc::FullPtr<" << task_type << "> typed_task = task_ptr.template Cast<" << task_type << ">();\n";
      oss << "      co_await " << method.method_name << "(typed_task, rctx);\n";
      oss << "      break;\n";
      oss << "    }\n";
    }

    oss << "    default: {\n";
    oss << "      // Unknown method - do nothing\n";
    oss << "      break;\n";
    oss << "    }\n";
    oss << "  }\n";
    oss << "  // co_return makes this a coroutine returning TaskResume\n";
    oss << "  co_return;\n";
    oss << "}\n";
    oss << "\n";
    oss << "void Runtime::SaveTask(chi::u32 method, chi::SaveTaskArchive& archive, \n";
    oss << "                        hipc::FullPtr<chi::Task> task_ptr) {\n";
    oss << "  switch (method) {\n";

    // Add SaveTask switch cases
    for (const auto& method : methods) {
      std::string task_type = GetTaskTypeName(method.method_name, chimod_name);
      oss << "    case Method::" << method.constant_name << ": {\n";
      oss << "      auto typed_task = task_ptr.template Cast<" << task_type << ">();\n";
      oss << "      archive << *typed_task.ptr_;\n";
      oss << "      break;\n";
      oss << "    }\n";
    }

    oss << "    default: {\n";
    oss << "      // Unknown method - do nothing\n";
    oss << "      break;\n";
    oss << "    }\n";
    oss << "  }\n";
    oss << "}\n";
    oss << "\n";
    oss << "void Runtime::LoadTask(chi::u32 method, chi::LoadTaskArchive& archive,\n";
    oss << "                        hipc::FullPtr<chi::Task> task_ptr) {\n";
    oss << "  switch (method) {\n";

    // Add LoadTask switch cases
    for (const auto& method : methods) {
      std::string task_type = GetTaskTypeName(method.method_name, chimod_name);
      oss << "    case Method::" << method.constant_name << ": {\n";
      oss << "      auto typed_task = task_ptr.template Cast<" << task_type << ">();\n";
      oss << "      archive >> *typed_task.ptr_;\n";
      oss << "      break;\n";
      oss << "    }\n";
    }

    oss << "    default: {\n";
    oss << "      // Unknown method - do nothing\n";
    oss << "      break;\n";
    oss << "    }\n";
    oss << "  }\n";
    oss << "}\n";
    oss << "\n";
    oss << "hipc::FullPtr<chi::Task> Runtime::AllocLoadTask(chi::u32 method, chi::LoadTaskArchive& archive) {\n";
    oss << "  hipc::FullPtr<chi::Task> task_ptr = NewTask(method);\n";
    oss << "  if (!task_ptr.IsNull()) {\n";
    oss << "    LoadTask(method, archive, task_ptr);\n";
    oss << "  }\n";
    oss << "  return task_ptr;\n";
    oss << "}\n";
    oss << "\n";
    oss << "void Runtime::LocalLoadTask(chi::u32 method, chi::DefaultLoadArchive& archive,\n";
    oss << "                            hipc::FullPtr<chi::Task> task_ptr) {\n";
    oss << "  switch (method) {\n";

    // Add LocalLoadTask switch cases
    for (const auto& method : methods) {
      std::string task_type = GetTaskTypeName(method.method_name, chimod_name);
      oss << "    case Method::" << method.constant_name << ": {\n";
      oss << "      auto typed_task = task_ptr.template Cast<" << task_type << ">();\n";
      oss << "      // Use archive operator which respects msg_type\n";
      oss << "      archive >> *typed_task.ptr_;\n";
      oss << "      break;\n";
      oss << "    }\n";
    }

    oss << "    default: {\n";
    oss << "      // Unknown method - do nothing\n";
    oss << "      break;\n";
    oss << "    }\n";
    oss << "  }\n";
    oss << "}\n";
    oss << "\n";
    oss << "hipc::FullPtr<chi::Task> Runtime::LocalAllocLoadTask(chi::u32 method, chi::DefaultLoadArchive& archive) {\n";
    oss << "  hipc::FullPtr<chi::Task> task_ptr = NewTask(method);\n";
    oss << "  if (!task_ptr.IsNull()) {\n";
    oss << "    LocalLoadTask(method, archive, task_ptr);\n";
    oss << "  }\n";
    oss << "  return task_ptr;\n";
    oss << "}\n";
    oss << "\n";
    oss << "void Runtime::LocalSaveTask(chi::u32 method, chi::DefaultSaveArchive& archive, \n";
    oss << "                             hipc::FullPtr<chi::Task> task_ptr) {\n";
    oss << "  switch (method) {\n";

    // Add LocalSaveTask switch cases
    for (const auto& method : methods) {
      std::string task_type = GetTaskTypeName(method.method_name, chimod_name);
      oss << "    case Method::" << method.constant_name << ": {\n";
      oss << "      auto typed_task = task_ptr.template Cast<" << task_type << ">();\n";
      oss << "      // Use archive operator which respects msg_type\n";
      oss << "      archive << *typed_task.ptr_;\n";
      oss << "      break;\n";
      oss << "    }\n";
    }

    oss << "    default: {\n";
    oss << "      // Unknown method - do nothing\n";
    oss << "      break;\n";
    oss << "    }\n";
    oss << "  }\n";
    oss << "}\n";
    oss << "\n";
    oss << "hipc::FullPtr<chi::Task> Runtime::NewCopyTask(chi::u32 method, hipc::FullPtr<chi::Task> orig_task_ptr, bool deep) {\n";
    oss << "  auto* ipc_manager = CHI_IPC;\n";
    oss << "  if (!ipc_manager) {\n";
    oss << "    return hipc::FullPtr<chi::Task>();\n";
    oss << "  }\n";
    oss << "  \n";
    oss << "  switch (method) {\n";

    // Add NewCopyTask switch cases
    for (const auto& method : methods) {
      std::string task_type = GetTaskTypeName(method.method_name, chimod_name);
      oss << "    case Method::" << method.constant_name << ": {\n";
      oss << "      // Allocate new task\n";
      oss << "      auto new_task_ptr = ipc_manager->NewTask<" << task_type << ">();\n";
      oss << "      if (!new_task_ptr.IsNull()) {\n";
      oss << "        // Copy task fields (includes base Task fields)\n";
      oss << "        auto task_typed = orig_task_ptr.template Cast<" << task_type << ">();\n";
      oss << "        new_task_ptr->Copy(task_typed);\n";
      oss << "        return new_task_ptr.template Cast<chi::Task>();\n";
      oss << "      }\n";
      oss << "      break;\n";
      oss << "    }\n";
    }

    oss << "    default: {\n";
    oss << "      // For unknown methods, create base Task copy\n";
      oss << "      auto new_task_ptr = ipc_manager->NewTask<chi::Task>();\n";
    oss << "      if (!new_task_ptr.IsNull()) {\n";
    oss << "        new_task_ptr->Copy(orig_task_ptr);\n";
    oss << "        return new_task_ptr;\n";
    oss << "      }\n";
    oss << "      break;\n";
    oss << "    }\n";
    oss << "  }\n";
    oss << "  \n";
    oss << "  (void)deep;    // Deep copy parameter reserved for future use\n";
    oss << "  return hipc::FullPtr<chi::Task>();\n";
    oss << "}\n";
    oss << "\n";
    oss << "hipc::FullPtr<chi::Task> Runtime::NewTask(chi::u32 method) {\n";
    oss << "  auto* ipc_manager = CHI_IPC;\n";
    oss << "  if (!ipc_manager) {\n";
    oss << "    return hipc::FullPtr<chi::Task>();\n";
    oss << "  }\n";
    oss << "  \n";
    oss << "  switch (method) {\n";

    // Add NewTask switch cases
    for (const auto& method : methods) {
      std::string task_type = GetTaskTypeName(method.method_name, chimod_name);
      oss << "    case Method::" << method.constant_name << ": {\n";
      oss << "      auto new_task_ptr = ipc_manager->NewTask<" << task_type << ">();\n";
      oss << "      return new_task_ptr.template Cast<chi::Task>();\n";
      oss << "    }\n";
    }

    oss << "    default: {\n";
    oss << "      // For unknown methods, return null pointer\n";
    oss << "      return hipc::FullPtr<chi::Task>();\n";
    oss << "    }\n";
    oss << "  }\n";
    oss << "}\n";
    oss << "\n";
    // Generate Aggregate method - dispatches to typed task's Aggregate
    oss << "void Runtime::Aggregate(chi::u32 method, hipc::FullPtr<chi::Task> orig_task,\n";
    oss << "                        const hipc::FullPtr<chi::Task>& replica_task) {\n";
    oss << "  switch (method) {\n";

    for (const auto& method : methods) {
      std::string task_type = GetTaskTypeName(method.method_name, chimod_name);
      oss << "    case Method::" << method.constant_name << ": {\n";
      oss << "      auto typed_task = orig_task.template Cast<" << task_type << ">();\n";
      oss << "      typed_task->Aggregate(replica_task);\n";
      oss << "      break;\n";
      oss << "    }\n";
    }

    oss << "    default: {\n";
    oss << "      orig_task->Aggregate(replica_task);\n";
    oss << "      break;\n";
    oss << "    }\n";
    oss << "  }\n";
    oss << "}\n";
    oss << "\n";

    // Generate DelTask method - dispatches to typed task deletion
    oss << "void Runtime::DelTask(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {\n";
    oss << "  auto* ipc_manager = CHI_IPC;\n";
    oss << "  if (!ipc_manager) return;\n";
    oss << "  switch (method) {\n";

    for (const auto& method : methods) {
      std::string task_type = GetTaskTypeName(method.method_name, chimod_name);
      oss << "    case Method::" << method.constant_name << ": {\n";
      oss << "      ipc_manager->DelTask(task_ptr.template Cast<" << task_type << ">());\n";
      oss << "      break;\n";
      oss << "    }\n";
    }

    oss << "    default: {\n";
    oss << "      ipc_manager->DelTask(task_ptr);\n";
    oss << "      break;\n";
    oss << "    }\n";
    oss << "  }\n";
    oss << "}\n";
    oss << "\n";
    oss << "} // namespace " << namespace_name << "::" << chimod_name << "\n";

    return oss.str();
  }

  /**
   * Generate GPU lib_exec header for a single ChiMod.
   * This is an includable header with switch-case overrides for the three
   * virtual methods (Run, LocalAllocLoadTask, LocalSaveTask).
   */
  std::string GenerateGpuLibExecHeader(const std::string& chimod_name, const YAML::Node& config,
                                        const std::string& repo_namespace) {
    std::string namespace_name = repo_namespace;
    std::string module_name = config["module_name"] ? config["module_name"].as<std::string>() : chimod_name;

    // Get GPU methods list
    std::vector<Method> gpu_methods;
    if (config["gpu_methods"] && config["gpu_methods"].IsSequence()) {
      auto all_methods = GetMethods(config);
      std::vector<std::string> gpu_method_names;
      for (const auto& m : config["gpu_methods"]) {
        gpu_method_names.push_back(m.as<std::string>());
      }
      for (const auto& m : all_methods) {
        for (const auto& gm : gpu_method_names) {
          if (m.constant_name == gm) {
            gpu_methods.push_back(m);
            break;
          }
        }
      }
    }

    std::ostringstream oss;
    oss << "// Auto-generated GPU lib_exec for " << module_name << "\n";
    oss << "// Include inside GpuRuntime class body\n";
    oss << "// This file is autogenerated - do not edit manually.\n";
    oss << "\n";

    // ====================================================================
    // Template helpers (LoadTaskTmpl, SaveTaskTmpl)
    // ====================================================================
    oss << "template <typename ArchiveT>\n";
    oss << "HSHM_GPU_FUN void LoadTaskTmpl(\n";
    oss << "    chi::u32 method, ArchiveT &archive,\n";
    oss << "    const hipc::FullPtr<chi::Task> &task) {\n";
    if (!gpu_methods.empty()) {
      oss << "  switch (method) {\n";
      for (const auto& method : gpu_methods) {
        std::string task_type = GetTaskTypeName(method.method_name, chimod_name);
        oss << "    case Method::" << method.constant_name << ": {\n";
        oss << "      auto typed = task.template Cast<" << task_type << ">();\n";
        oss << "      if (archive.GetMsgType() == chi::LocalMsgType::kSerializeIn)\n";
        oss << "        typed->SerializeIn(archive);\n";
        oss << "      else\n";
        oss << "        typed->SerializeOut(archive);\n";
        oss << "      break;\n";
        oss << "    }\n";
      }
      oss << "    default: break;\n";
      oss << "  }\n";
    } else {
      oss << "  (void)method; (void)archive; (void)task;\n";
    }
    oss << "}\n\n";

    oss << "template <typename ArchiveT>\n";
    oss << "HSHM_GPU_FUN void SaveTaskTmpl(\n";
    oss << "    chi::u32 method, ArchiveT &archive,\n";
    oss << "    const hipc::FullPtr<chi::Task> &task) {\n";
    if (!gpu_methods.empty()) {
      oss << "  switch (method) {\n";
      for (const auto& method : gpu_methods) {
        std::string task_type = GetTaskTypeName(method.method_name, chimod_name);
        oss << "    case Method::" << method.constant_name << ":\n";
        oss << "      task.template Cast<" << task_type << ">()->SerializeOut(archive);\n";
        oss << "      break;\n";
      }
      oss << "    default: break;\n";
      oss << "  }\n";
    } else {
      oss << "  (void)method; (void)archive; (void)task;\n";
    }
    oss << "}\n\n";

    // ====================================================================
    // Static dispatch functions (called via function pointers)
    // ====================================================================

    // RunImpl — address taken by GpuRuntime ctor below. HSHM_INDIRECTLY_CALLABLE
    // is required by DPC++'s sycl_ext_oneapi_virtual_functions extension when
    // -fsycl-allow-func-ptr is unavailable; under CUDA/ROCm and the default
    // SYCL flag set it expands to nothing.
    oss << "HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN chi::gpu::TaskResume RunImpl(\n";
    oss << "    chi::gpu::Container *self_, chi::u32 method,\n";
    oss << "    hipc::FullPtr<chi::Task> task_ptr, chi::gpu::RunContext &rctx) {\n";
    oss << "  auto *self = static_cast<GpuRuntime *>(self_);\n";
    if (!gpu_methods.empty()) {
      oss << "  switch (method) {\n";
      for (const auto& method : gpu_methods) {
        std::string task_type = GetTaskTypeName(method.method_name, chimod_name);
        oss << "    case Method::" << method.constant_name << ":\n";
        oss << "      co_await self->" << method.method_name << "(task_ptr.template Cast<" << task_type << ">(), rctx);\n";
        oss << "      break;\n";
      }
      oss << "    default: break;\n";
      oss << "  }\n";
    } else {
      oss << "  (void)self; (void)method; (void)task_ptr; (void)rctx;\n";
    }
    oss << "  co_return;\n";
    oss << "}\n\n";

    // AllocTaskImpl — uses NewTaskExec: [Task | RunContext | stack]
    oss << "HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN chi::gpu::TaskContextBlock AllocTaskImpl(\n";
    oss << "    chi::gpu::Container *self_, chi::u32 method, size_t stack_size) {\n";
    if (!gpu_methods.empty()) {
      // Phase 10: bind g_ipc_manager_ptr from self_->ipc_mgr_ so CHI_IPC\n
      // under SYCL resolves to the kernel-scope IpcManager. Worker writes\n
      // self_->ipc_mgr_ before each dispatch. CUDA falls back to the\n
      // __shared__ singleton via GetBlockIpcManager and ignores this.\n
      oss << "  [[maybe_unused]] auto *g_ipc_manager_ptr = self_->ipc_mgr_;\n";
      oss << "  auto *ipc = CHI_IPC;\n";
      oss << "  switch (method) {\n";
      for (const auto& method : gpu_methods) {
        std::string task_type = GetTaskTypeName(method.method_name, chimod_name);
        oss << "    case Method::" << method.constant_name << ": {\n";
        oss << "      auto fp = ipc->template NewTaskExec<" << task_type << ">(stack_size);\n";
        oss << "      if (fp.IsNull()) return {hipc::FullPtr<chi::Task>::GetNull(), nullptr};\n";
        oss << "      auto *rctx = reinterpret_cast<chi::gpu::RunContext *>(\n";
        oss << "          reinterpret_cast<char *>(fp.ptr_) + sizeof(" << task_type << "));\n";
        oss << "      new (rctx) chi::gpu::RunContext();\n";
        oss << "      rctx->InitStack(reinterpret_cast<char *>(rctx) + sizeof(chi::gpu::RunContext), stack_size);\n";
        oss << "      return {fp.template Cast<chi::Task>(), rctx};\n";
        oss << "    }\n";
      }
      oss << "    default: return {hipc::FullPtr<chi::Task>::GetNull(), nullptr};\n";
      oss << "  }\n";
    } else {
      oss << "  (void)self_; (void)method; (void)stack_size;\n";
      oss << "  return {hipc::FullPtr<chi::Task>::GetNull(), nullptr};\n";
    }
    oss << "}\n\n";

    // AllocLoadTaskDefaultImpl
    oss << "HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN hipc::FullPtr<chi::Task> AllocLoadTaskDefaultImpl(\n";
    oss << "    chi::gpu::Container *self_, chi::u32 method, chi::GpuLoadTaskArchive &ar) {\n";
    oss << "  auto *self = static_cast<GpuRuntime *>(self_);\n";
    oss << "  auto block = self->alloc_task_(self_, method, 0);\n";
    oss << "  if (block.task_ptr.IsNull()) return block.task_ptr;\n";
    oss << "  ar.SetMsgType(chi::LocalMsgType::kSerializeIn);\n";
    oss << "  self->LoadTaskTmpl(method, ar, block.task_ptr);\n";
    oss << "  return block.task_ptr;\n";
    oss << "}\n\n";

    // AllocLoadDeserImpl — single dispatch: alloc + deserialize from WrapLoadArchive
    oss << "HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN chi::gpu::TaskContextBlock AllocLoadDeserImpl(\n";
    oss << "    chi::gpu::Container *self_, chi::u32 method,\n";
    oss << "    size_t stack_size, chi::GpuLoadTaskArchive &ar) {\n";
    oss << "  auto *self = static_cast<GpuRuntime *>(self_);\n";
    oss << "  auto block = AllocTaskImpl(self_, method, stack_size);\n";
    oss << "  if (!block.task_ptr.IsNull()) {\n";
    oss << "    ar.SetMsgType(chi::LocalMsgType::kSerializeIn);\n";
    oss << "    self->LoadTaskTmpl(method, ar, block.task_ptr);\n";
    oss << "  }\n";
    oss << "  return block;\n";
    oss << "}\n\n";

    // LoadTaskDefaultImpl
    oss << "HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN void LoadTaskDefaultImpl(\n";
    oss << "    chi::gpu::Container *self_, chi::u32 method,\n";
    oss << "    chi::GpuLoadTaskArchive &ar, const hipc::FullPtr<chi::Task> &task) {\n";
    oss << "  ar.SetMsgType(chi::LocalMsgType::kSerializeIn);\n";
    oss << "  static_cast<GpuRuntime *>(self_)->LoadTaskTmpl(method, ar, task);\n";
    oss << "}\n\n";

    // SaveTaskDefaultImpl
    oss << "HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN void SaveTaskDefaultImpl(\n";
    oss << "    chi::gpu::Container *self_, chi::u32 method,\n";
    oss << "    chi::GpuSaveTaskArchive &ar, const hipc::FullPtr<chi::Task> &task) {\n";
    oss << "  static_cast<GpuRuntime *>(self_)->SaveTaskTmpl(method, ar, task);\n";
    oss << "}\n\n";

    // LoadTaskOutputImpl
    oss << "HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN void LoadTaskOutputImpl(\n";
    oss << "    chi::gpu::Container *self_, chi::u32 method,\n";
    oss << "    chi::GpuLoadTaskArchive &ar, const hipc::FullPtr<chi::Task> &task) {\n";
    oss << "  ar.SetMsgType(chi::LocalMsgType::kSerializeOut);\n";
    oss << "  static_cast<GpuRuntime *>(self_)->LoadTaskTmpl(method, ar, task);\n";
    oss << "}\n\n";

    // DestroyTaskImpl
    oss << "HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN void DestroyTaskImpl(\n";
    oss << "    chi::gpu::Container *self_, chi::u32 method,\n";
    oss << "    hipc::FullPtr<chi::Task> &task) {\n";
    oss << "  if (task.IsNull()) return;\n";
    if (!gpu_methods.empty()) {
      oss << "  switch (method) {\n";
      for (const auto& method : gpu_methods) {
        std::string task_type = GetTaskTypeName(method.method_name, chimod_name);
        oss << "    case Method::" << method.constant_name << ":\n";
        // Extract unqualified name for destructor:
        // 1. Strip template args first (find first '<')
        // 2. Then strip namespace (find last '::' in what remains)
        std::string dtor_name = task_type;
        auto angle = dtor_name.find('<');
        if (angle != std::string::npos) dtor_name = dtor_name.substr(0, angle);
        auto last_colon = dtor_name.rfind("::");
        if (last_colon != std::string::npos) dtor_name = dtor_name.substr(last_colon + 2);
        oss << "      task.template Cast<" << task_type << ">().ptr_->~" << dtor_name << "();\n";
        oss << "      break;\n";
      }
      oss << "    default: task.ptr_->~Task(); break;\n";
      oss << "  }\n";
    } else {
      oss << "  task.ptr_->~Task();\n";
    }
    oss << "}\n\n";

    // ====================================================================
    // Constructor: wire up function pointer table
    // ====================================================================
    oss << "HSHM_GPU_FUN GpuRuntime() {\n";
    oss << "  run_ = &RunImpl;\n";
    oss << "  alloc_task_ = &AllocTaskImpl;\n";
    oss << "  alloc_load_deser_ = &AllocLoadDeserImpl;\n";
    oss << "  alloc_load_task_ = &AllocLoadTaskDefaultImpl;\n";
    oss << "  load_task_ = &LoadTaskDefaultImpl;\n";
    oss << "  save_task_ = &SaveTaskDefaultImpl;\n";
    oss << "  load_task_output_ = &LoadTaskOutputImpl;\n";
    oss << "  destroy_task_ = &DestroyTaskImpl;\n";
    oss << "}\n";

    return oss.str();
  }

  /**
   * Generate repo-level GPU work orchestrator modules header.
   * Includes all GPU runtime headers and provides allocation kernel/function.
   */
  std::string GenerateGpuOrchestratorModulesHeader(
      const std::vector<std::pair<std::string, std::string>>& gpu_modules) {
    std::ostringstream oss;
    oss << "// Auto-generated GPU work orchestrator module registry\n";
    oss << "// This file is autogenerated - do not edit manually.\n";
    oss << "\n";
    oss << "#ifndef CHIMAERA_AUTOGEN_GPU_WORK_ORCHESTRATOR_MODULES_H_\n";
    oss << "#define CHIMAERA_AUTOGEN_GPU_WORK_ORCHESTRATOR_MODULES_H_\n";
    oss << "\n";

    // gpu/gpu_ipc_manager.h must be visible BEFORE any chimod's _tasks.h,\n
    // since CHI_IPC->NewTask<...> dereferences chi::gpu::IpcManager, which\n
    // ipc_manager.h only forward-declares. Required by the SYCL build path;\n
    // CUDA TUs typically pulled it in via the GPU compiler's include order.
    oss << "#include \"chimaera/gpu/gpu_ipc_manager.h\"\n";
    oss << "\n";

    // Include all GPU runtime headers
    for (const auto& [chimod_name, module_name] : gpu_modules) {
      oss << "#include \"" << repo_namespace_ << "/" << module_name << "/" << chimod_name << "_gpu_runtime.h\"\n";
    }
    oss << "\n";
    oss << "#include \"chimaera/gpu/container.h\"\n";
    oss << "#include \"chimaera/types.h\"\n";
    oss << "#include \"hermes_shm/util/gpu_api.h\"\n";
    oss << "#include <cstring>\n";
    oss << "\n";
    oss << "#if HSHM_ENABLE_SYCL\n";
    oss << "#include <sycl/sycl.hpp>\n";
    oss << "#endif\n";
    oss << "\n";
    oss << "namespace chi {\n";
    oss << "namespace gpu {\n";
    oss << "\n";

    // ----- CUDA / ROCm allocation kernel ----------------------------------
    oss << "#if HSHM_ENABLE_CUDA || HSHM_ENABLE_ROCM\n";
    oss << "/**\n";
    oss << " * Kernel to allocate a GPU container by module index.\n";
    oss << " * Runs in the orchestrator's CUDA/HIP module context so vtables\n";
    oss << " * are correct.\n";
    oss << " */\n";
    oss << "__global__ void _gpu_alloc_container(Container **out, u32 module_id,\n";
    oss << "                                      const PoolId *pid, u32 cid) {\n";
    oss << "  Container *obj = nullptr;\n";
    oss << "  switch (module_id) {\n";
    for (size_t i = 0; i < gpu_modules.size(); ++i) {
      const auto& [chimod_name, module_name] = gpu_modules[i];
      oss << "    case " << i << ": obj = new " << repo_namespace_ << "::" << chimod_name << "::GpuRuntime(); break;\n";
    }
    oss << "    default: break;\n";
    oss << "  }\n";
    oss << "  if (obj) obj->Init(*pid, cid);\n";
    oss << "  *out = obj;\n";
    oss << "}\n";
    oss << "#endif  // HSHM_ENABLE_CUDA || HSHM_ENABLE_ROCM\n";
    oss << "\n";

    // ----- Module-id table -------------------------------------------------
    oss << "/**\n";
    oss << " * Map ChiMod name to module ID for GPU container allocation.\n";
    oss << " */\n";
    oss << "inline u32 GetGpuModuleId(const char *chimod_name) {\n";
    for (size_t i = 0; i < gpu_modules.size(); ++i) {
      const auto& [chimod_name, module_name] = gpu_modules[i];
      std::string full_name = repo_namespace_ + "_" + chimod_name;
      oss << "  if (strcmp(chimod_name, \"" << full_name << "\") == 0) return " << i << ";\n";
    }
    oss << "  return 0xFFFFFFFF;\n";
    oss << "}\n";
    oss << "\n";

    // Per-module sizeof helper, used by the SYCL allocator to size the
    // device USM region. Each chimod's GpuRuntime has its own (small)
    // function-pointer-table layout so the size differs.
    oss << "/**\n";
    oss << " * sizeof(GpuRuntime) for the given module ID. Used to pre-size\n";
    oss << " * device USM before placement-new in SYCL device code, which\n";
    oss << " * cannot call ::operator new for arbitrary types.\n";
    oss << " */\n";
    oss << "inline size_t GetGpuModuleSize(u32 module_id) {\n";
    oss << "  switch (module_id) {\n";
    for (size_t i = 0; i < gpu_modules.size(); ++i) {
      const auto& [chimod_name, module_name] = gpu_modules[i];
      oss << "    case " << i << ": return sizeof(" << repo_namespace_ << "::" << chimod_name << "::GpuRuntime);\n";
    }
    oss << "    default: return 0;\n";
    oss << "  }\n";
    oss << "}\n";
    oss << "\n";

    // ----- Host-side dispatch ---------------------------------------------
    oss << "/**\n";
    oss << " * Host function to allocate a GPU container.\n";
    oss << " * @return Device pointer to allocated container, or nullptr\n";
    oss << " */\n";
    oss << "inline void *AllocGpuContainerHost(const PoolId &pool_id, u32 container_id,\n";
    oss << "                                    const char *chimod_name) {\n";
    oss << "  u32 module_id = GetGpuModuleId(chimod_name);\n";
    oss << "  if (module_id == 0xFFFFFFFF) return nullptr;\n";
    oss << "\n";
    oss << "#if HSHM_ENABLE_CUDA || HSHM_ENABLE_ROCM\n";
    oss << "  void *stream = hshm::GpuApi::CreateStream();\n";
    oss << "  Container **d_out = hshm::GpuApi::Malloc<Container *>(sizeof(Container *));\n";
    oss << "  PoolId *d_pid = hshm::GpuApi::Malloc<PoolId>(sizeof(PoolId));\n";
    oss << "  hshm::GpuApi::Memcpy(d_pid, &pool_id, sizeof(PoolId));\n";
    oss << "  _gpu_alloc_container<<<1, 1, 0,\n";
    oss << "      static_cast<cudaStream_t>(stream)>>>(d_out, module_id, d_pid, container_id);\n";
    oss << "  hshm::GpuApi::Synchronize(stream);\n";
    oss << "  Container *h_ptr = nullptr;\n";
    oss << "  hshm::GpuApi::Memcpy(&h_ptr, d_out, sizeof(Container *));\n";
    oss << "  hshm::GpuApi::Free(d_out);\n";
    oss << "  hshm::GpuApi::Free(d_pid);\n";
    oss << "  hshm::GpuApi::DestroyStream(stream);\n";
    oss << "  return static_cast<void *>(h_ptr);\n";
    oss << "#elif HSHM_ENABLE_SYCL\n";
    oss << "  // SYCL path: size the USM region from GetGpuModuleSize, then\n";
    oss << "  // submit a single_task that placement-news the right concrete\n";
    oss << "  // GpuRuntime subclass (placement new is allowed in SYCL device\n";
    oss << "  // code; ::operator new for arbitrary types is not).\n";
    oss << "  size_t obj_size = GetGpuModuleSize(module_id);\n";
    oss << "  if (obj_size == 0) return nullptr;\n";
    oss << "  auto &q = hshm::GpuApi::SyclQueue();\n";
    oss << "  void *d_obj = sycl::malloc_device(obj_size, q);\n";
    oss << "  PoolId *d_pid = sycl::malloc_device<PoolId>(1, q);\n";
    oss << "  q.memcpy(d_pid, &pool_id, sizeof(PoolId)).wait();\n";
    oss << "  q.submit([&](sycl::handler &cgh) {\n";
    oss << "    cgh.single_task<class chimaera_gpu_alloc_container_sycl_kernel>([=]() {\n";
    oss << "      Container *obj = nullptr;\n";
    oss << "      switch (module_id) {\n";
    for (size_t i = 0; i < gpu_modules.size(); ++i) {
      const auto& [chimod_name, module_name] = gpu_modules[i];
      oss << "        case " << i << ":\n";
      oss << "          obj = new (d_obj) " << repo_namespace_ << "::" << chimod_name << "::GpuRuntime();\n";
      oss << "          break;\n";
    }
    oss << "        default: break;\n";
    oss << "      }\n";
    oss << "      if (obj) obj->Init(*d_pid, container_id);\n";
    oss << "    });\n";
    oss << "  }).wait();\n";
    oss << "  sycl::free(d_pid, q);\n";
    oss << "  return d_obj;\n";
    oss << "#else\n";
    oss << "  (void)pool_id; (void)container_id; (void)module_id;\n";
    oss << "  return nullptr;\n";
    oss << "#endif\n";
    oss << "}\n";
    oss << "\n";
    oss << "}  // namespace gpu\n";
    oss << "}  // namespace chi\n";
    oss << "\n";
    oss << "#endif  // CHIMAERA_AUTOGEN_GPU_WORK_ORCHESTRATOR_MODULES_H_\n";

    return oss.str();
  }

  /**
   * Generate autogen files for a single ChiMod
   */
  void GenerateChiModFiles(const std::string& chimod_name) {
    HIPRINT("Generating files for ChiMod: {}", chimod_name);

    // Load ChiMod configuration
    YAML::Node config;
    try {
      config = LoadChiModConfig(chimod_name);
    } catch (const std::runtime_error& e) {
      HLOG(kWarning, "{}", e.what());
      return;
    }

    // Create include autogen directory for methods header
    // Structure: [chimod_directory]/include/[namespace]/[module_name]/autogen/
    std::string module_name = config["module_name"] ? config["module_name"].as<std::string>() : chimod_name;
    fs::path include_autogen_dir = repo_path_ / chimod_name / "include" / repo_namespace_ / module_name / "autogen";
    fs::create_directories(include_autogen_dir);

    // Create src autogen directory for lib_exec source
    fs::path src_autogen_dir = repo_path_ / chimod_name / "src" / "autogen";
    fs::create_directories(src_autogen_dir);

    // Generate methods header
    std::string methods_content = GenerateMethodsHeader(chimod_name, config, repo_namespace_);
    fs::path methods_file = include_autogen_dir / (chimod_name + "_methods.h");
    std::ofstream methods_stream(methods_file);
    if (!methods_stream) {
      throw std::runtime_error("Failed to create methods file: " + methods_file.string());
    }
    methods_stream << methods_content;
    methods_stream.close();
    HIPRINT("  Generated: {}", methods_file.string());

    // Generate lib_exec source file
    std::string lib_exec_content = GenerateLibExecSource(chimod_name, config, repo_namespace_);
    fs::path lib_exec_file = src_autogen_dir / (chimod_name + "_lib_exec.cc");
    std::ofstream lib_exec_stream(lib_exec_file);
    if (!lib_exec_stream) {
      throw std::runtime_error("Failed to create lib_exec file: " + lib_exec_file.string());
    }
    lib_exec_stream << lib_exec_content;
    lib_exec_stream.close();
    HIPRINT("  Generated: {}", lib_exec_file.string());

    // Generate GPU lib_exec header if module has GPU support
    if (config["has_gpu"] && config["has_gpu"].as<bool>(false)) {
      std::string gpu_lib_exec_content = GenerateGpuLibExecHeader(chimod_name, config, repo_namespace_);
      fs::path gpu_lib_exec_file = include_autogen_dir / (chimod_name + "_gpu_lib_exec.h");
      std::ofstream gpu_lib_exec_stream(gpu_lib_exec_file);
      if (!gpu_lib_exec_stream) {
        throw std::runtime_error("Failed to create GPU lib_exec file: " + gpu_lib_exec_file.string());
      }
      gpu_lib_exec_stream << gpu_lib_exec_content;
      gpu_lib_exec_stream.close();
      HIPRINT("  Generated: {}", gpu_lib_exec_file.string());
    }
  }

  /**
   * Refresh all ChiMods in the repository
   */
  void DoRefreshRepo() {
    YAML::Node repo_config = LoadRepoConfig();

    if (!repo_config["modules"] || !repo_config["modules"].IsSequence()) {
      throw std::runtime_error("No modules found in repository configuration");
    }

    std::vector<std::string> modules;
    for (const auto& module : repo_config["modules"]) {
      modules.push_back(module.as<std::string>());
    }

    HIPRINT("Refreshing ChiMod repository: {}", repo_path_.string());
    std::string module_list;
    for (size_t i = 0; i < modules.size(); ++i) {
      if (i > 0) module_list += ", ";
      module_list += modules[i];
    }
    HIPRINT("Found {} modules: {}", modules.size(), module_list);
    HIPRINT("");

    // Collect GPU modules for repo-level header generation
    std::vector<std::pair<std::string, std::string>> gpu_modules;

    for (const auto& chimod_name : modules) {
      GenerateChiModFiles(chimod_name);

      // Check if module has GPU support
      try {
        YAML::Node config = LoadChiModConfig(chimod_name);
        if (config["has_gpu"] && config["has_gpu"].as<bool>(false)) {
          std::string module_name = config["module_name"] ? config["module_name"].as<std::string>() : chimod_name;
          gpu_modules.emplace_back(chimod_name, module_name);
        }
      } catch (...) {}

      HIPRINT("");
    }

    // Generate repo-level GPU work orchestrator modules header
    if (!gpu_modules.empty()) {
      fs::path src_autogen_dir = repo_path_ / ".." / "src" / "autogen";
      fs::create_directories(src_autogen_dir);
      std::string orchestrator_content = GenerateGpuOrchestratorModulesHeader(gpu_modules);
      fs::path orchestrator_file = src_autogen_dir / "gpu_work_orchestrator_modules.h";
      std::ofstream orchestrator_stream(orchestrator_file);
      if (orchestrator_stream) {
        orchestrator_stream << orchestrator_content;
        orchestrator_stream.close();
        HIPRINT("Generated repo-level GPU header: {}", orchestrator_file.string());
      }
    }

    HIPRINT("Repository refresh complete!");
  }
};

/**
 * Print usage information for the repo refresh subcommand
 *
 * @param program_name The name of the program for display
 */
static void PrintRefreshRepoUsage(const char* program_name) {
  HIPRINT("Usage: {} <chimod_repo_path>", program_name);
  HIPRINT("");
  HIPRINT("Autogenerate ChiMod libexec and methods files");
  HIPRINT("");
  HIPRINT("Examples:");
  HIPRINT("  {} /path/to/chimods", program_name);
  HIPRINT("  {} .", program_name);
}

/**
 * Entry point for the repo refresh subcommand
 *
 * @param argc Argument count (after stripping "chimaera repo refresh")
 * @param argv Argument values
 * @return 0 on success, 1 on failure
 */
int RefreshRepo(int argc, char** argv) {
  if (argc != 1) {
    PrintRefreshRepoUsage("chimaera repo refresh");
    return 1;
  }

  std::string repo_path = argv[0];

  try {
    ChiModGenerator generator(repo_path);
    generator.DoRefreshRepo();
    return 0;
  } catch (const std::exception& e) {
    HLOG(kError, "{}", e.what());
    return 1;
  }
}
