/**
 * Auto-generated execution implementation for admin ChiMod
 * Implements Container virtual APIs (Run, SaveTask, LoadTask, NewCopyTask, NewTask)
 * using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "clio_runtime/admin/admin_runtime.h"
#include "clio_runtime/admin/autogen/admin_methods.h"
#include <clio_runtime/clio_runtime.h>
#include <clio_runtime/task.h>  // For TaskResume coroutine return type

namespace clio::run::admin {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Init(const clio::run::PoolId &pool_id, const std::string &pool_name,
                   clio::run::u32 container_id) {
  // Call base class initialization
  clio::run::Container::Init(pool_id, pool_name, container_id);

  // Initialize the client for this ChiMod
  client_ = Client(pool_id);

  // Initialize per-method load prediction model
  DefineModel(Method::kMaxMethodId);
  SetMethodNames(Method::GetMethodNames());
}

clio::run::TaskResume Runtime::Run(clio::run::u32 method, clio::run::shared_ptr<clio::run::Task> task_ptr) {
  CLIO_TASK_BODY_BEGIN
  switch (method) {
    case Method::kCreate: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      CLIO_CO_AWAIT(Create(typed_task));
      break;
    }
    case Method::kDestroy: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      CLIO_CO_AWAIT(Destroy(typed_task));
      break;
    }
    case Method::kMonitor: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      CLIO_CO_AWAIT(Monitor(typed_task));
      break;
    }
    case Method::kGetOrCreatePool: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      CLIO_CO_AWAIT(GetOrCreatePool(typed_task));
      break;
    }
    case Method::kDestroyPool: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<DestroyPoolTask>();
      CLIO_CO_AWAIT(DestroyPool(typed_task));
      break;
    }
    case Method::kStopRuntime: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<StopRuntimeTask>();
      CLIO_CO_AWAIT(StopRuntime(typed_task));
      break;
    }
    case Method::kFlush: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<FlushTask>();
      CLIO_CO_AWAIT(Flush(typed_task));
      break;
    }
    case Method::kSend: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<SendTask>();
      CLIO_CO_AWAIT(Send(typed_task));
      break;
    }
    case Method::kRecv: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<RecvTask>();
      CLIO_CO_AWAIT(Recv(typed_task));
      break;
    }
    case Method::kClientConnect: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<ClientConnectTask>();
      CLIO_CO_AWAIT(ClientConnect(typed_task));
      break;
    }
    case Method::kSubmitBatch: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<SubmitBatchTask>();
      CLIO_CO_AWAIT(SubmitBatch(typed_task));
      break;
    }
    case Method::kWreapDeadIpcs: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<WreapDeadIpcsTask>();
      CLIO_CO_AWAIT(WreapDeadIpcs(typed_task));
      break;
    }
    case Method::kClientRecv: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<ClientRecvTask>();
      CLIO_CO_AWAIT(ClientRecv(typed_task));
      break;
    }
    case Method::kClientSend: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<ClientSendTask>();
      CLIO_CO_AWAIT(ClientSend(typed_task));
      break;
    }
    case Method::kRegisterMemory: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<RegisterMemoryTask>();
      CLIO_CO_AWAIT(RegisterMemory(typed_task));
      break;
    }
    case Method::kRestartContainers: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<RestartContainersTask>();
      CLIO_CO_AWAIT(RestartContainers(typed_task));
      break;
    }
    case Method::kAddNode: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<AddNodeTask>();
      CLIO_CO_AWAIT(AddNode(typed_task));
      break;
    }
    case Method::kChangeAddressTable: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<ChangeAddressTableTask>();
      CLIO_CO_AWAIT(ChangeAddressTable(typed_task));
      break;
    }
    case Method::kMigrateContainers: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<MigrateContainersTask>();
      CLIO_CO_AWAIT(MigrateContainers(typed_task));
      break;
    }
    case Method::kHeartbeat: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<HeartbeatTask>();
      CLIO_CO_AWAIT(Heartbeat(typed_task));
      break;
    }
    case Method::kHeartbeatProbe: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<HeartbeatProbeTask>();
      CLIO_CO_AWAIT(HeartbeatProbe(typed_task));
      break;
    }
    case Method::kProbeRequest: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<ProbeRequestTask>();
      CLIO_CO_AWAIT(ProbeRequest(typed_task));
      break;
    }
    case Method::kRecoverContainers: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<RecoverContainersTask>();
      CLIO_CO_AWAIT(RecoverContainers(typed_task));
      break;
    }
    case Method::kSystemMonitor: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<SystemMonitorTask>();
      CLIO_CO_AWAIT(SystemMonitor(typed_task));
      break;
    }
    case Method::kAnnounceShutdown: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<AnnounceShutdownTask>();
      CLIO_CO_AWAIT(AnnounceShutdown(typed_task));
      break;
    }
    case Method::kRegisterGpuContainer: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<RegisterGpuContainerTask>();
      CLIO_CO_AWAIT(RegisterGpuContainer(typed_task));
      break;
    }
    case Method::kListContainers: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<ListContainersTask>();
      CLIO_CO_AWAIT(ListContainers(typed_task));
      break;
    }
    case Method::kQueryTaskProgress: {
      auto& typed_task = task_ptr.template Cast<QueryTaskProgressTask>();
      CLIO_CO_AWAIT(QueryTaskProgress(typed_task));
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
  CLIO_CO_RETURN;
  CLIO_TASK_BODY_END
}

void Runtime::SaveTask(clio::run::u32 method, clio::run::SaveTaskArchive& archive, 
                        clio::run::shared_ptr<clio::run::Task>& task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      archive << *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      archive << *typed_task;
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      archive << *typed_task;
      break;
    }
    case Method::kGetOrCreatePool: {
      auto& typed_task = task_ptr.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      archive << *typed_task;
      break;
    }
    case Method::kDestroyPool: {
      auto& typed_task = task_ptr.template Cast<DestroyPoolTask>();
      archive << *typed_task;
      break;
    }
    case Method::kStopRuntime: {
      auto& typed_task = task_ptr.template Cast<StopRuntimeTask>();
      archive << *typed_task;
      break;
    }
    case Method::kFlush: {
      auto& typed_task = task_ptr.template Cast<FlushTask>();
      archive << *typed_task;
      break;
    }
    case Method::kSend: {
      auto& typed_task = task_ptr.template Cast<SendTask>();
      archive << *typed_task;
      break;
    }
    case Method::kRecv: {
      auto& typed_task = task_ptr.template Cast<RecvTask>();
      archive << *typed_task;
      break;
    }
    case Method::kClientConnect: {
      auto& typed_task = task_ptr.template Cast<ClientConnectTask>();
      archive << *typed_task;
      break;
    }
    case Method::kSubmitBatch: {
      auto& typed_task = task_ptr.template Cast<SubmitBatchTask>();
      archive << *typed_task;
      break;
    }
    case Method::kWreapDeadIpcs: {
      auto& typed_task = task_ptr.template Cast<WreapDeadIpcsTask>();
      archive << *typed_task;
      break;
    }
    case Method::kClientRecv: {
      auto& typed_task = task_ptr.template Cast<ClientRecvTask>();
      archive << *typed_task;
      break;
    }
    case Method::kClientSend: {
      auto& typed_task = task_ptr.template Cast<ClientSendTask>();
      archive << *typed_task;
      break;
    }
    case Method::kRegisterMemory: {
      auto& typed_task = task_ptr.template Cast<RegisterMemoryTask>();
      archive << *typed_task;
      break;
    }
    case Method::kRestartContainers: {
      auto& typed_task = task_ptr.template Cast<RestartContainersTask>();
      archive << *typed_task;
      break;
    }
    case Method::kAddNode: {
      auto& typed_task = task_ptr.template Cast<AddNodeTask>();
      archive << *typed_task;
      break;
    }
    case Method::kChangeAddressTable: {
      auto& typed_task = task_ptr.template Cast<ChangeAddressTableTask>();
      archive << *typed_task;
      break;
    }
    case Method::kMigrateContainers: {
      auto& typed_task = task_ptr.template Cast<MigrateContainersTask>();
      archive << *typed_task;
      break;
    }
    case Method::kHeartbeat: {
      auto& typed_task = task_ptr.template Cast<HeartbeatTask>();
      archive << *typed_task;
      break;
    }
    case Method::kHeartbeatProbe: {
      auto& typed_task = task_ptr.template Cast<HeartbeatProbeTask>();
      archive << *typed_task;
      break;
    }
    case Method::kProbeRequest: {
      auto& typed_task = task_ptr.template Cast<ProbeRequestTask>();
      archive << *typed_task;
      break;
    }
    case Method::kRecoverContainers: {
      auto& typed_task = task_ptr.template Cast<RecoverContainersTask>();
      archive << *typed_task;
      break;
    }
    case Method::kSystemMonitor: {
      auto& typed_task = task_ptr.template Cast<SystemMonitorTask>();
      archive << *typed_task;
      break;
    }
    case Method::kAnnounceShutdown: {
      auto& typed_task = task_ptr.template Cast<AnnounceShutdownTask>();
      archive << *typed_task;
      break;
    }
    case Method::kRegisterGpuContainer: {
      auto& typed_task = task_ptr.template Cast<RegisterGpuContainerTask>();
      archive << *typed_task;
      break;
    }
    case Method::kListContainers: {
      auto& typed_task = task_ptr.template Cast<ListContainersTask>();
      archive << *typed_task;
      break;
    }
    case Method::kQueryTaskProgress: {
      auto& typed_task = task_ptr.template Cast<QueryTaskProgressTask>();
      archive << *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadTask(clio::run::u32 method, clio::run::LoadTaskArchive& archive,
                        clio::run::shared_ptr<clio::run::Task>& task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kGetOrCreatePool: {
      auto& typed_task = task_ptr.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      archive >> *typed_task;
      break;
    }
    case Method::kDestroyPool: {
      auto& typed_task = task_ptr.template Cast<DestroyPoolTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kStopRuntime: {
      auto& typed_task = task_ptr.template Cast<StopRuntimeTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kFlush: {
      auto& typed_task = task_ptr.template Cast<FlushTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kSend: {
      auto& typed_task = task_ptr.template Cast<SendTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kRecv: {
      auto& typed_task = task_ptr.template Cast<RecvTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kClientConnect: {
      auto& typed_task = task_ptr.template Cast<ClientConnectTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kSubmitBatch: {
      auto& typed_task = task_ptr.template Cast<SubmitBatchTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kWreapDeadIpcs: {
      auto& typed_task = task_ptr.template Cast<WreapDeadIpcsTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kClientRecv: {
      auto& typed_task = task_ptr.template Cast<ClientRecvTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kClientSend: {
      auto& typed_task = task_ptr.template Cast<ClientSendTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kRegisterMemory: {
      auto& typed_task = task_ptr.template Cast<RegisterMemoryTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kRestartContainers: {
      auto& typed_task = task_ptr.template Cast<RestartContainersTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kAddNode: {
      auto& typed_task = task_ptr.template Cast<AddNodeTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kChangeAddressTable: {
      auto& typed_task = task_ptr.template Cast<ChangeAddressTableTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kMigrateContainers: {
      auto& typed_task = task_ptr.template Cast<MigrateContainersTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kHeartbeat: {
      auto& typed_task = task_ptr.template Cast<HeartbeatTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kHeartbeatProbe: {
      auto& typed_task = task_ptr.template Cast<HeartbeatProbeTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kProbeRequest: {
      auto& typed_task = task_ptr.template Cast<ProbeRequestTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kRecoverContainers: {
      auto& typed_task = task_ptr.template Cast<RecoverContainersTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kSystemMonitor: {
      auto& typed_task = task_ptr.template Cast<SystemMonitorTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kAnnounceShutdown: {
      auto& typed_task = task_ptr.template Cast<AnnounceShutdownTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kRegisterGpuContainer: {
      auto& typed_task = task_ptr.template Cast<RegisterGpuContainerTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kListContainers: {
      auto& typed_task = task_ptr.template Cast<ListContainersTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kQueryTaskProgress: {
      auto& typed_task = task_ptr.template Cast<QueryTaskProgressTask>();
      archive >> *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

clio::run::shared_ptr<clio::run::Task> Runtime::AllocLoadTask(clio::run::u32 method, clio::run::LoadTaskArchive& archive) {
  clio::run::shared_ptr<clio::run::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalLoadTask(clio::run::u32 method, clio::run::DefaultLoadArchive& archive,
                            clio::run::shared_ptr<clio::run::Task>& task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kGetOrCreatePool: {
      auto& typed_task = task_ptr.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kDestroyPool: {
      auto& typed_task = task_ptr.template Cast<DestroyPoolTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kStopRuntime: {
      auto& typed_task = task_ptr.template Cast<StopRuntimeTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kFlush: {
      auto& typed_task = task_ptr.template Cast<FlushTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kSend: {
      auto& typed_task = task_ptr.template Cast<SendTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kRecv: {
      auto& typed_task = task_ptr.template Cast<RecvTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kClientConnect: {
      auto& typed_task = task_ptr.template Cast<ClientConnectTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kSubmitBatch: {
      auto& typed_task = task_ptr.template Cast<SubmitBatchTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kWreapDeadIpcs: {
      auto& typed_task = task_ptr.template Cast<WreapDeadIpcsTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kClientRecv: {
      auto& typed_task = task_ptr.template Cast<ClientRecvTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kClientSend: {
      auto& typed_task = task_ptr.template Cast<ClientSendTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kRegisterMemory: {
      auto& typed_task = task_ptr.template Cast<RegisterMemoryTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kRestartContainers: {
      auto& typed_task = task_ptr.template Cast<RestartContainersTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kAddNode: {
      auto& typed_task = task_ptr.template Cast<AddNodeTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kChangeAddressTable: {
      auto& typed_task = task_ptr.template Cast<ChangeAddressTableTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kMigrateContainers: {
      auto& typed_task = task_ptr.template Cast<MigrateContainersTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kHeartbeat: {
      auto& typed_task = task_ptr.template Cast<HeartbeatTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kHeartbeatProbe: {
      auto& typed_task = task_ptr.template Cast<HeartbeatProbeTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kProbeRequest: {
      auto& typed_task = task_ptr.template Cast<ProbeRequestTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kRecoverContainers: {
      auto& typed_task = task_ptr.template Cast<RecoverContainersTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kSystemMonitor: {
      auto& typed_task = task_ptr.template Cast<SystemMonitorTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kAnnounceShutdown: {
      auto& typed_task = task_ptr.template Cast<AnnounceShutdownTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kRegisterGpuContainer: {
      auto& typed_task = task_ptr.template Cast<RegisterGpuContainerTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kListContainers: {
      auto& typed_task = task_ptr.template Cast<ListContainersTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kQueryTaskProgress: {
      auto& typed_task = task_ptr.template Cast<QueryTaskProgressTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

clio::run::shared_ptr<clio::run::Task> Runtime::LocalAllocLoadTask(clio::run::u32 method, clio::run::DefaultLoadArchive& archive) {
  clio::run::shared_ptr<clio::run::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LocalLoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalSaveTask(clio::run::u32 method, clio::run::DefaultSaveArchive& archive, 
                             clio::run::shared_ptr<clio::run::Task>& task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kGetOrCreatePool: {
      auto& typed_task = task_ptr.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kDestroyPool: {
      auto& typed_task = task_ptr.template Cast<DestroyPoolTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kStopRuntime: {
      auto& typed_task = task_ptr.template Cast<StopRuntimeTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kFlush: {
      auto& typed_task = task_ptr.template Cast<FlushTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kSend: {
      auto& typed_task = task_ptr.template Cast<SendTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kRecv: {
      auto& typed_task = task_ptr.template Cast<RecvTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kClientConnect: {
      auto& typed_task = task_ptr.template Cast<ClientConnectTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kSubmitBatch: {
      auto& typed_task = task_ptr.template Cast<SubmitBatchTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kWreapDeadIpcs: {
      auto& typed_task = task_ptr.template Cast<WreapDeadIpcsTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kClientRecv: {
      auto& typed_task = task_ptr.template Cast<ClientRecvTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kClientSend: {
      auto& typed_task = task_ptr.template Cast<ClientSendTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kRegisterMemory: {
      auto& typed_task = task_ptr.template Cast<RegisterMemoryTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kRestartContainers: {
      auto& typed_task = task_ptr.template Cast<RestartContainersTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kAddNode: {
      auto& typed_task = task_ptr.template Cast<AddNodeTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kChangeAddressTable: {
      auto& typed_task = task_ptr.template Cast<ChangeAddressTableTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kMigrateContainers: {
      auto& typed_task = task_ptr.template Cast<MigrateContainersTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kHeartbeat: {
      auto& typed_task = task_ptr.template Cast<HeartbeatTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kHeartbeatProbe: {
      auto& typed_task = task_ptr.template Cast<HeartbeatProbeTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kProbeRequest: {
      auto& typed_task = task_ptr.template Cast<ProbeRequestTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kRecoverContainers: {
      auto& typed_task = task_ptr.template Cast<RecoverContainersTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kSystemMonitor: {
      auto& typed_task = task_ptr.template Cast<SystemMonitorTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kAnnounceShutdown: {
      auto& typed_task = task_ptr.template Cast<AnnounceShutdownTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kRegisterGpuContainer: {
      auto& typed_task = task_ptr.template Cast<RegisterGpuContainerTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kListContainers: {
      auto& typed_task = task_ptr.template Cast<ListContainersTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kQueryTaskProgress: {
      auto& typed_task = task_ptr.template Cast<QueryTaskProgressTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

clio::run::shared_ptr<clio::run::Task> Runtime::NewCopyTask(clio::run::u32 method, clio::run::shared_ptr<clio::run::Task>& orig_task_ptr, bool deep) {
  auto* ipc_manager = CLIO_IPC;
  if (!ipc_manager) {
    return clio::run::shared_ptr<clio::run::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<CreateTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<CreateTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kDestroy: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<DestroyTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<DestroyTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kMonitor: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<MonitorTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<MonitorTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kGetOrCreatePool: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<admin::GetOrCreatePoolTask<admin::CreateParams>>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kDestroyPool: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DestroyPoolTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<DestroyPoolTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<DestroyPoolTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kStopRuntime: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<StopRuntimeTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<StopRuntimeTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<StopRuntimeTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kFlush: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<FlushTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<FlushTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<FlushTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kSend: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<SendTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<SendTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<SendTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kRecv: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<RecvTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<RecvTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<RecvTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kClientConnect: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ClientConnectTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<ClientConnectTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<ClientConnectTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kSubmitBatch: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<SubmitBatchTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<SubmitBatchTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<SubmitBatchTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kWreapDeadIpcs: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<WreapDeadIpcsTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<WreapDeadIpcsTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<WreapDeadIpcsTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kClientRecv: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ClientRecvTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<ClientRecvTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<ClientRecvTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kClientSend: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ClientSendTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<ClientSendTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<ClientSendTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kRegisterMemory: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<RegisterMemoryTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<RegisterMemoryTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<RegisterMemoryTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kRestartContainers: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<RestartContainersTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<RestartContainersTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<RestartContainersTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kAddNode: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<AddNodeTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<AddNodeTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<AddNodeTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kChangeAddressTable: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ChangeAddressTableTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<ChangeAddressTableTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<ChangeAddressTableTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kMigrateContainers: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<MigrateContainersTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<MigrateContainersTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<MigrateContainersTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kHeartbeat: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<HeartbeatTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<HeartbeatTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<HeartbeatTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kHeartbeatProbe: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<HeartbeatProbeTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<HeartbeatProbeTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<HeartbeatProbeTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kProbeRequest: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ProbeRequestTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<ProbeRequestTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<ProbeRequestTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kRecoverContainers: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<RecoverContainersTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<RecoverContainersTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<RecoverContainersTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kSystemMonitor: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<SystemMonitorTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<SystemMonitorTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<SystemMonitorTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kAnnounceShutdown: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<AnnounceShutdownTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<AnnounceShutdownTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<AnnounceShutdownTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kRegisterGpuContainer: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<RegisterGpuContainerTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<RegisterGpuContainerTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<RegisterGpuContainerTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kListContainers: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ListContainersTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<ListContainersTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<ListContainersTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kQueryTaskProgress: {
      auto new_task_ptr = ipc_manager->NewTask<QueryTaskProgressTask>();
      if (!new_task_ptr.IsNull()) {
        auto& task_typed = orig_task_ptr.template Cast<QueryTaskProgressTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<QueryTaskProgressTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    default: {
      // For unknown methods, create base Task copy
      auto new_task_ptr = ipc_manager->NewTask<clio::run::Task>();
      if (!new_task_ptr.IsNull()) {
        new_task_ptr->Copy(ctp::ipc::FullPtr<clio::run::Task>(orig_task_ptr.get()));
        return new_task_ptr;
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
  return clio::run::shared_ptr<clio::run::Task>();
}

clio::run::shared_ptr<clio::run::Task> Runtime::NewTask(clio::run::u32 method) {
  auto* ipc_manager = CLIO_IPC;
  if (!ipc_manager) {
    return clio::run::shared_ptr<clio::run::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kDestroy: {
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kMonitor: {
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kGetOrCreatePool: {
      auto new_task_ptr = ipc_manager->NewTask<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kDestroyPool: {
      auto new_task_ptr = ipc_manager->NewTask<DestroyPoolTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kStopRuntime: {
      auto new_task_ptr = ipc_manager->NewTask<StopRuntimeTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kFlush: {
      auto new_task_ptr = ipc_manager->NewTask<FlushTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kSend: {
      auto new_task_ptr = ipc_manager->NewTask<SendTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kRecv: {
      auto new_task_ptr = ipc_manager->NewTask<RecvTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kClientConnect: {
      auto new_task_ptr = ipc_manager->NewTask<ClientConnectTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kSubmitBatch: {
      auto new_task_ptr = ipc_manager->NewTask<SubmitBatchTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kWreapDeadIpcs: {
      auto new_task_ptr = ipc_manager->NewTask<WreapDeadIpcsTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kClientRecv: {
      auto new_task_ptr = ipc_manager->NewTask<ClientRecvTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kClientSend: {
      auto new_task_ptr = ipc_manager->NewTask<ClientSendTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kRegisterMemory: {
      auto new_task_ptr = ipc_manager->NewTask<RegisterMemoryTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kRestartContainers: {
      auto new_task_ptr = ipc_manager->NewTask<RestartContainersTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kAddNode: {
      auto new_task_ptr = ipc_manager->NewTask<AddNodeTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kChangeAddressTable: {
      auto new_task_ptr = ipc_manager->NewTask<ChangeAddressTableTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kMigrateContainers: {
      auto new_task_ptr = ipc_manager->NewTask<MigrateContainersTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kHeartbeat: {
      auto new_task_ptr = ipc_manager->NewTask<HeartbeatTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kHeartbeatProbe: {
      auto new_task_ptr = ipc_manager->NewTask<HeartbeatProbeTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kProbeRequest: {
      auto new_task_ptr = ipc_manager->NewTask<ProbeRequestTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kRecoverContainers: {
      auto new_task_ptr = ipc_manager->NewTask<RecoverContainersTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kSystemMonitor: {
      auto new_task_ptr = ipc_manager->NewTask<SystemMonitorTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kAnnounceShutdown: {
      auto new_task_ptr = ipc_manager->NewTask<AnnounceShutdownTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kRegisterGpuContainer: {
      auto new_task_ptr = ipc_manager->NewTask<RegisterGpuContainerTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kListContainers: {
      auto new_task_ptr = ipc_manager->NewTask<ListContainersTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kQueryTaskProgress: {
      auto new_task_ptr = ipc_manager->NewTask<QueryTaskProgressTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    default: {
      // For unknown methods, return null pointer
      return clio::run::shared_ptr<clio::run::Task>();
    }
  }
}

void Runtime::AggregateOut(clio::run::u32 method, clio::run::shared_ptr<clio::run::Task>& orig_task,
                        const clio::run::shared_ptr<clio::run::Task>& replica_task) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = orig_task.template Cast<CreateTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = orig_task.template Cast<DestroyTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = orig_task.template Cast<MonitorTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kGetOrCreatePool: {
      auto& typed_task = orig_task.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kDestroyPool: {
      auto& typed_task = orig_task.template Cast<DestroyPoolTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kStopRuntime: {
      auto& typed_task = orig_task.template Cast<StopRuntimeTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kFlush: {
      auto& typed_task = orig_task.template Cast<FlushTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kSend: {
      auto& typed_task = orig_task.template Cast<SendTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kRecv: {
      auto& typed_task = orig_task.template Cast<RecvTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kClientConnect: {
      auto& typed_task = orig_task.template Cast<ClientConnectTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kSubmitBatch: {
      auto& typed_task = orig_task.template Cast<SubmitBatchTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kWreapDeadIpcs: {
      auto& typed_task = orig_task.template Cast<WreapDeadIpcsTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kClientRecv: {
      auto& typed_task = orig_task.template Cast<ClientRecvTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kClientSend: {
      auto& typed_task = orig_task.template Cast<ClientSendTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kRegisterMemory: {
      auto& typed_task = orig_task.template Cast<RegisterMemoryTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kRestartContainers: {
      auto& typed_task = orig_task.template Cast<RestartContainersTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kAddNode: {
      auto& typed_task = orig_task.template Cast<AddNodeTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kChangeAddressTable: {
      auto& typed_task = orig_task.template Cast<ChangeAddressTableTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kMigrateContainers: {
      auto& typed_task = orig_task.template Cast<MigrateContainersTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kHeartbeat: {
      auto& typed_task = orig_task.template Cast<HeartbeatTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kHeartbeatProbe: {
      auto& typed_task = orig_task.template Cast<HeartbeatProbeTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kProbeRequest: {
      auto& typed_task = orig_task.template Cast<ProbeRequestTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kRecoverContainers: {
      auto& typed_task = orig_task.template Cast<RecoverContainersTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kSystemMonitor: {
      auto& typed_task = orig_task.template Cast<SystemMonitorTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kAnnounceShutdown: {
      auto& typed_task = orig_task.template Cast<AnnounceShutdownTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kRegisterGpuContainer: {
      auto& typed_task = orig_task.template Cast<RegisterGpuContainerTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kListContainers: {
      auto& typed_task = orig_task.template Cast<ListContainersTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kQueryTaskProgress: {
      auto& typed_task = orig_task.template Cast<QueryTaskProgressTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    default: {
      orig_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
  }
}


} // namespace clio::run::admin
