/*
 * Copyright (c) 2024, Gnosis Research Center, Illinois Institute of Technology
 * All rights reserved.
 *
 * This file is part of IOWarp Core.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef CLIO_RUNTIME_INCLUDE_TASK_STAT_MODEL_H_
#define CLIO_RUNTIME_INCLUDE_TASK_STAT_MODEL_H_

#include <string>
#include <unordered_map>

#include "clio_runtime/types.h"

namespace clio::run {

/**
 * The learned coefficients for ONE method of a container.
 *
 * Mirrors the four per-method vectors a Container keeps (method_model_,
 * method_mape_, method_model_wall_, method_mape_wall_) for a single method id.
 */
struct MethodStatWeights {
  float cpu_coef_ = 1.0f;   ///< predicted_cpu_us = cpu_coef_ * (compute + 1)
  float cpu_mape_ = 0.0f;   ///< EMA of |predicted - real| / real for CPU
  float wall_coef_ = 1.0f;  ///< predicted_wall_us = wall_coef_ * (wall + 1)
  float wall_mape_ = 0.0f;  ///< EMA of |predicted - real| / real for wall clock
};

/**
 * A name-keyed snapshot of a container's task-stat model, as persisted to
 * disk.
 *
 * Keyed by method NAME rather than method id on purpose: method ids are
 * positions in an autogenerated enum, so adding or reordering a chimod's
 * methods renumbers them. Restoring an id-keyed file after such a change would
 * silently graft one method's learned coefficient onto another and quietly
 * corrupt every scheduling decision that reads it. Names survive renumbering;
 * a method whose name is absent from the file simply keeps its seed value, and
 * a name in the file that the binary no longer defines is ignored.
 */
struct TaskStatModelSnapshot {
  std::string chimod_name_;  ///< ChiMod that owns the pool (provenance only)
  std::string pool_name_;    ///< Pool the model was learned on (provenance only)
  u32 container_id_ = 0;     ///< Container it was learned on (provenance only)
  float learning_rate_ = 0.0f;  ///< SGD rate in force when saved (provenance)
  /** method name -> learned coefficients */
  std::unordered_map<std::string, MethodStatWeights> methods_;

  /** @return true if the snapshot carries no per-method weights. */
  bool Empty() const { return methods_.empty(); }

  /**
   * Write the snapshot to `path` as YAML, creating parent directories.
   * The write is atomic: it goes to `path`.tmp and is then renamed over
   * `path`, so a crash mid-save cannot leave a truncated file that the next
   * startup would load as authoritative.
   * @return true on success.
   */
  bool Save(const std::string &path) const;

  /**
   * Read a snapshot previously written by Save(). A missing file is NOT an
   * error condition worth logging loudly — it is the normal first-run case —
   * and returns false with the snapshot left empty.
   * @return true if the file existed and parsed.
   */
  bool Load(const std::string &path);
};

/**
 * Canonical on-disk location of a container's persisted model:
 *   <conf_dir>/models/<chimod_name>.<pool_name>.<node_id>.<container_id>.yaml
 *
 * Per container (issue #994): the model is learned from the tasks ONE
 * container executed on ONE node's hardware. A pool may host several
 * containers on a node (its own plus any recovered from a dead peer), and for
 * a chimod like bdev those can back entirely different devices, so their
 * coefficients must neither be merged nor restored onto each other. Keeping
 * the node id in the name as well means a recovered container's file cannot
 * collide with the file the same container id writes on its home node.
 * Characters that are not path-safe in the pool name are replaced with '_'
 * (CTE pool names are paths, e.g. "/mnt/hdd/cte").
 *
 * @return the full path, or an empty string if no ConfigManager is available.
 */
std::string TaskStatModelPath(const std::string &chimod_name,
                              const std::string &pool_name, u32 node_id,
                              u32 container_id);

}  // namespace clio::run

#endif  // CLIO_RUNTIME_INCLUDE_TASK_STAT_MODEL_H_
