/**
 * Auto-generated execution implementation for compressor ChiMod
 * Implements Container virtual APIs (Run, SaveTask, LoadTask, NewCopyTask, NewTask)
 * using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "clio_cte/compressor/compressor_runtime.h"
#include "clio_cte/compressor/autogen/compressor_methods.h"
#include <clio_runtime/clio_runtime.h>
#include <clio_runtime/task.h>  // For TaskResume coroutine return type

namespace clio::cte::compressor {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Init(const clio::run::PoolId &pool_id, const std::string &pool_name,
                   clio::run::u32 container_id) {
  // Call base class initialization
  clio::run::Container::Init(pool_id, pool_name, container_id);

  // Initialize the client for this ChiMod
  client_ = Client(pool_id);

  // Initialize per-method load prediction model
  DefineModel(Method::kMaxMethodId);
  SetMethodNames(Method::GetMethodNames());
}

clio::run::TaskResume Runtime::Run(clio::run::u32 method, ctp::ipc::FullPtr<clio::run::Task> task_ptr, clio::run::RunContext& rctx) {
  CLIO_TASK_BODY_BEGIN
  switch (method) {
    case Method::kCreate: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<CreateTask> typed_task = task_ptr.template Cast<CreateTask>();
      CLIO_CO_AWAIT(Create(typed_task, rctx));
      break;
    }
    case Method::kDestroy: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<DestroyTask> typed_task = task_ptr.template Cast<DestroyTask>();
      CLIO_CO_AWAIT(Destroy(typed_task, rctx));
      break;
    }
    case Method::kMonitor: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<MonitorTask> typed_task = task_ptr.template Cast<MonitorTask>();
      CLIO_CO_AWAIT(Monitor(typed_task, rctx));
      break;
    }
    case Method::kDynamicSchedule: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<DynamicScheduleTask> typed_task = task_ptr.template Cast<DynamicScheduleTask>();
      CLIO_CO_AWAIT(DynamicSchedule(typed_task, rctx));
      break;
    }
    case Method::kCompress: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<CompressTask> typed_task = task_ptr.template Cast<CompressTask>();
      CLIO_CO_AWAIT(Compress(typed_task, rctx));
      break;
    }
    case Method::kDecompress: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<DecompressTask> typed_task = task_ptr.template Cast<DecompressTask>();
      CLIO_CO_AWAIT(Decompress(typed_task, rctx));
      break;
    }
    case Method::kPollNodeLoad: {
      ctp::ipc::FullPtr<PollNodeLoadTask> typed_task = task_ptr.template Cast<PollNodeLoadTask>();
      CLIO_CO_AWAIT(PollNodeLoad(typed_task, rctx));
      break;
    }
    case Method::kPollConsumers: {
      ctp::ipc::FullPtr<PollConsumersTask> typed_task = task_ptr.template Cast<PollConsumersTask>();
      CLIO_CO_AWAIT(PollConsumers(typed_task, rctx));
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
  CLIO_CO_RETURN;
  CLIO_TASK_BODY_END
}

void Runtime::SaveTask(clio::run::u32 method, clio::run::SaveTaskArchive& archive, 
                        ctp::ipc::FullPtr<clio::run::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDynamicSchedule: {
      auto typed_task = task_ptr.template Cast<DynamicScheduleTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kCompress: {
      auto typed_task = task_ptr.template Cast<CompressTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDecompress: {
      auto typed_task = task_ptr.template Cast<DecompressTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kPollNodeLoad: {
      auto typed_task = task_ptr.template Cast<PollNodeLoadTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kPollConsumers: {
      auto typed_task = task_ptr.template Cast<PollConsumersTask>();
      archive << *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadTask(clio::run::u32 method, clio::run::LoadTaskArchive& archive,
                        ctp::ipc::FullPtr<clio::run::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDynamicSchedule: {
      auto typed_task = task_ptr.template Cast<DynamicScheduleTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kCompress: {
      auto typed_task = task_ptr.template Cast<CompressTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDecompress: {
      auto typed_task = task_ptr.template Cast<DecompressTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kPollNodeLoad: {
      auto typed_task = task_ptr.template Cast<PollNodeLoadTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kPollConsumers: {
      auto typed_task = task_ptr.template Cast<PollConsumersTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

ctp::ipc::FullPtr<clio::run::Task> Runtime::AllocLoadTask(clio::run::u32 method, clio::run::LoadTaskArchive& archive) {
  ctp::ipc::FullPtr<clio::run::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalLoadTask(clio::run::u32 method, clio::run::DefaultLoadArchive& archive,
                            ctp::ipc::FullPtr<clio::run::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDynamicSchedule: {
      auto typed_task = task_ptr.template Cast<DynamicScheduleTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kCompress: {
      auto typed_task = task_ptr.template Cast<CompressTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDecompress: {
      auto typed_task = task_ptr.template Cast<DecompressTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kPollNodeLoad: {
      auto typed_task = task_ptr.template Cast<PollNodeLoadTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kPollConsumers: {
      auto typed_task = task_ptr.template Cast<PollConsumersTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

ctp::ipc::FullPtr<clio::run::Task> Runtime::LocalAllocLoadTask(clio::run::u32 method, clio::run::DefaultLoadArchive& archive) {
  ctp::ipc::FullPtr<clio::run::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LocalLoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalSaveTask(clio::run::u32 method, clio::run::DefaultSaveArchive& archive, 
                             ctp::ipc::FullPtr<clio::run::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDynamicSchedule: {
      auto typed_task = task_ptr.template Cast<DynamicScheduleTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kCompress: {
      auto typed_task = task_ptr.template Cast<CompressTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDecompress: {
      auto typed_task = task_ptr.template Cast<DecompressTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kPollNodeLoad: {
      auto typed_task = task_ptr.template Cast<PollNodeLoadTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kPollConsumers: {
      auto typed_task = task_ptr.template Cast<PollConsumersTask>();
      archive << *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

ctp::ipc::FullPtr<clio::run::Task> Runtime::NewCopyTask(clio::run::u32 method, ctp::ipc::FullPtr<clio::run::Task> orig_task_ptr, bool deep) {
  auto* ipc_manager = CLIO_IPC;
  if (!ipc_manager) {
    return ctp::ipc::FullPtr<clio::run::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<CreateTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kDestroy: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<DestroyTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kMonitor: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<MonitorTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kDynamicSchedule: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DynamicScheduleTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<DynamicScheduleTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kCompress: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<CompressTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<CompressTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kDecompress: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DecompressTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<DecompressTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kPollNodeLoad: {
      auto new_task_ptr = ipc_manager->NewTask<PollNodeLoadTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<PollNodeLoadTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kPollConsumers: {
      auto new_task_ptr = ipc_manager->NewTask<PollConsumersTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<PollConsumersTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    default: {
      // For unknown methods, create base Task copy
      auto new_task_ptr = ipc_manager->NewTask<clio::run::Task>();
      if (!new_task_ptr.IsNull()) {
        new_task_ptr->Copy(orig_task_ptr);
        return new_task_ptr;
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
  return ctp::ipc::FullPtr<clio::run::Task>();
}

ctp::ipc::FullPtr<clio::run::Task> Runtime::NewTask(clio::run::u32 method) {
  auto* ipc_manager = CLIO_IPC;
  if (!ipc_manager) {
    return ctp::ipc::FullPtr<clio::run::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kDestroy: {
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kMonitor: {
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kDynamicSchedule: {
      auto new_task_ptr = ipc_manager->NewTask<DynamicScheduleTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kCompress: {
      auto new_task_ptr = ipc_manager->NewTask<CompressTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kDecompress: {
      auto new_task_ptr = ipc_manager->NewTask<DecompressTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kPollNodeLoad: {
      auto new_task_ptr = ipc_manager->NewTask<PollNodeLoadTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kPollConsumers: {
      auto new_task_ptr = ipc_manager->NewTask<PollConsumersTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    default: {
      // For unknown methods, return null pointer
      return ctp::ipc::FullPtr<clio::run::Task>();
    }
  }
}

void Runtime::AggregateOut(clio::run::u32 method, ctp::ipc::FullPtr<clio::run::Task> orig_task,
                        const ctp::ipc::FullPtr<clio::run::Task>& replica_task) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = orig_task.template Cast<CreateTask>();
      typed_task->AggregateOut(replica_task);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = orig_task.template Cast<DestroyTask>();
      typed_task->AggregateOut(replica_task);
      break;
    }
    case Method::kMonitor: {
      auto typed_task = orig_task.template Cast<MonitorTask>();
      typed_task->AggregateOut(replica_task);
      break;
    }
    case Method::kDynamicSchedule: {
      auto typed_task = orig_task.template Cast<DynamicScheduleTask>();
      typed_task->AggregateOut(replica_task);
      break;
    }
    case Method::kCompress: {
      auto typed_task = orig_task.template Cast<CompressTask>();
      typed_task->AggregateOut(replica_task);
      break;
    }
    case Method::kDecompress: {
      auto typed_task = orig_task.template Cast<DecompressTask>();
      typed_task->AggregateOut(replica_task);
      break;
    }
    case Method::kPollNodeLoad: {
      auto typed_task = orig_task.template Cast<PollNodeLoadTask>();
      typed_task->AggregateOut(replica_task);
      break;
    }
    case Method::kPollConsumers: {
      auto typed_task = orig_task.template Cast<PollConsumersTask>();
      typed_task->AggregateOut(replica_task);
      break;
    }
    default: {
      orig_task->AggregateOut(replica_task);
      break;
    }
  }
}

void Runtime::DelTask(clio::run::u32 method, ctp::ipc::FullPtr<clio::run::Task> task_ptr) {
  auto* ipc_manager = CLIO_IPC;
  if (!ipc_manager) return;
  switch (method) {
    case Method::kCreate: {
      ipc_manager->DelTask(task_ptr.template Cast<CreateTask>());
      break;
    }
    case Method::kDestroy: {
      ipc_manager->DelTask(task_ptr.template Cast<DestroyTask>());
      break;
    }
    case Method::kMonitor: {
      ipc_manager->DelTask(task_ptr.template Cast<MonitorTask>());
      break;
    }
    case Method::kDynamicSchedule: {
      ipc_manager->DelTask(task_ptr.template Cast<DynamicScheduleTask>());
      break;
    }
    case Method::kCompress: {
      ipc_manager->DelTask(task_ptr.template Cast<CompressTask>());
      break;
    }
    case Method::kDecompress: {
      ipc_manager->DelTask(task_ptr.template Cast<DecompressTask>());
      break;
    }
    case Method::kPollNodeLoad: {
      ipc_manager->DelTask(task_ptr.template Cast<PollNodeLoadTask>());
      break;
    }
    case Method::kPollConsumers: {
      ipc_manager->DelTask(task_ptr.template Cast<PollConsumersTask>());
      break;
    }
    default: {
      ipc_manager->DelTask(task_ptr);
      break;
    }
  }
}

} // namespace clio::cte::compressor
