// Auto-generated GPU lib_exec for admin
// Include inside GpuRuntime class body
// This file is autogenerated - do not edit manually.

template <typename ArchiveT>
HSHM_GPU_FUN void LoadTaskTmpl(
    chi::u32 method, ArchiveT &archive,
    const hipc::FullPtr<chi::Task> &task) {
  (void)method; (void)archive; (void)task;
}

template <typename ArchiveT>
HSHM_GPU_FUN void SaveTaskTmpl(
    chi::u32 method, ArchiveT &archive,
    const hipc::FullPtr<chi::Task> &task) {
  (void)method; (void)archive; (void)task;
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN void RunImpl(
    chi::gpu::Container *self_, chi::u32 method,
    hipc::FullPtr<chi::Task> task_ptr, chi::gpu::RunContext &rctx) {
  auto *self = static_cast<GpuRuntime *>(self_);
  (void)self; (void)method; (void)task_ptr; (void)rctx;
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN hipc::FullPtr<chi::Task> AllocTaskImpl(
    chi::gpu::Container *self_, chi::u32 method) {
  (void)self_; (void)method;
  return hipc::FullPtr<chi::Task>::GetNull();
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN hipc::FullPtr<chi::Task> AllocLoadTaskDefaultImpl(
    chi::gpu::Container *self_, chi::u32 method, chi::GpuLoadTaskArchive &ar) {
  auto *self = static_cast<GpuRuntime *>(self_);
  auto task_ptr = self->alloc_task_(self_, method);
  if (task_ptr.IsNull()) return task_ptr;
  ar.SetMsgType(chi::LocalMsgType::kSerializeIn);
  self->LoadTaskTmpl(method, ar, task_ptr);
  return task_ptr;
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN hipc::FullPtr<chi::Task> AllocLoadDeserImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::GpuLoadTaskArchive &ar) {
  auto *self = static_cast<GpuRuntime *>(self_);
  auto task_ptr = AllocTaskImpl(self_, method);
  if (!task_ptr.IsNull()) {
    ar.SetMsgType(chi::LocalMsgType::kSerializeIn);
    self->LoadTaskTmpl(method, ar, task_ptr);
  }
  return task_ptr;
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN void LoadTaskDefaultImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::GpuLoadTaskArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  ar.SetMsgType(chi::LocalMsgType::kSerializeIn);
  static_cast<GpuRuntime *>(self_)->LoadTaskTmpl(method, ar, task);
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN void SaveTaskDefaultImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::GpuSaveTaskArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  static_cast<GpuRuntime *>(self_)->SaveTaskTmpl(method, ar, task);
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN void LoadTaskOutputImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::GpuLoadTaskArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  ar.SetMsgType(chi::LocalMsgType::kSerializeOut);
  static_cast<GpuRuntime *>(self_)->LoadTaskTmpl(method, ar, task);
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN void DestroyTaskImpl(
    chi::gpu::Container *self_, chi::u32 method,
    hipc::FullPtr<chi::Task> &task) {
  if (task.IsNull()) return;
  task.ptr_->~Task();
}

HSHM_GPU_FUN GpuRuntime() {
  run_ = &RunImpl;
  fixup_task_ = nullptr;
  alloc_task_ = &AllocTaskImpl;
  alloc_load_deser_ = &AllocLoadDeserImpl;
  alloc_load_task_ = &AllocLoadTaskDefaultImpl;
  load_task_ = &LoadTaskDefaultImpl;
  save_task_ = &SaveTaskDefaultImpl;
  load_task_output_ = &LoadTaskOutputImpl;
  destroy_task_ = &DestroyTaskImpl;
}
