/**
 * Auto-generated execution implementation for core ChiMod
 * Implements Container virtual APIs (Run, SaveTask, LoadTask, NewCopyTask, NewTask)
 * using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "clio_cte/core/core_runtime.h"
#include "clio_cte/core/autogen/core_methods.h"
#include <clio_runtime/clio_runtime.h>
#include <clio_runtime/task.h>  // For TaskResume coroutine return type

namespace clio::cte::core {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Init(const clio::run::PoolId &pool_id, const std::string &pool_name,
                   clio::run::u32 container_id) {
  // Call base class initialization
  clio::run::Container::Init(pool_id, pool_name, container_id);

  // Initialize the client for this ChiMod
  client_ = Client(pool_id);

  // Initialize per-method load prediction model
  DefineModel(Method::kMaxMethodId);
  SetMethodNames(Method::GetMethodNames());
}

void Runtime::Restart(const clio::run::PoolId &pool_id, const std::string &pool_name,
                      clio::run::u32 container_id) {
  is_restart_ = true;
  Init(pool_id, pool_name, container_id);
}

clio::run::TaskResume Runtime::Run(clio::run::u32 method, clio::run::shared_ptr<clio::run::Task> task_ptr) {
  CLIO_TASK_BODY_BEGIN
  switch (method) {
    case Method::kCreate: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      CLIO_CO_AWAIT(Create(typed_task));
      break;
    }
    case Method::kDestroy: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      CLIO_CO_AWAIT(Destroy(typed_task));
      break;
    }
    case Method::kMonitor: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      CLIO_CO_AWAIT(Monitor(typed_task));
      break;
    }
    case Method::kRegisterTarget: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<RegisterTargetTask>();
      CLIO_CO_AWAIT(RegisterTarget(typed_task));
      break;
    }
    case Method::kUnregisterTarget: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<UnregisterTargetTask>();
      CLIO_CO_AWAIT(UnregisterTarget(typed_task));
      break;
    }
    case Method::kListTargets: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<ListTargetsTask>();
      CLIO_CO_AWAIT(ListTargets(typed_task));
      break;
    }
    case Method::kStatTargets: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<StatTargetsTask>();
      CLIO_CO_AWAIT(StatTargets(typed_task));
      break;
    }
    case Method::kGetOrCreateTag: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      CLIO_CO_AWAIT(GetOrCreateTag(typed_task));
      break;
    }
    case Method::kPutBlob: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<PutBlobTask>();
      CLIO_CO_AWAIT(PutBlob(typed_task));
      break;
    }
    case Method::kGetBlob: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<GetBlobTask>();
      CLIO_CO_AWAIT(GetBlob(typed_task));
      break;
    }
    case Method::kReorganizeBlob: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<ReorganizeBlobTask>();
      CLIO_CO_AWAIT(ReorganizeBlob(typed_task));
      break;
    }
    case Method::kPodPutBlob: {
      auto& typed_task = task_ptr.template Cast<PodPutBlobTask>();
      CLIO_CO_AWAIT(PodPutBlob(typed_task));
      break;
    }
    case Method::kPodGetBlob: {
      auto& typed_task = task_ptr.template Cast<PodGetBlobTask>();
      CLIO_CO_AWAIT(PodGetBlob(typed_task));
      break;
    }
    case Method::kPodReorganizeBlob: {
      auto& typed_task = task_ptr.template Cast<PodReorganizeBlobTask>();
      CLIO_CO_AWAIT(PodReorganizeBlob(typed_task));
      break;
    }
    case Method::kDynamicReorganize: {
      auto& typed_task = task_ptr.template Cast<DynamicReorganizeTask>();
      CLIO_CO_AWAIT(DynamicReorganize(typed_task));
      break;
    }
    case Method::kDelBlob: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<DelBlobTask>();
      CLIO_CO_AWAIT(DelBlob(typed_task));
      break;
    }
    case Method::kTruncateBlob: {
      auto& typed_task = task_ptr.template Cast<TruncateBlobTask>();
      CLIO_CO_AWAIT(TruncateBlob(typed_task));
      break;
    }
    case Method::kDelTag: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<DelTagTask>();
      CLIO_CO_AWAIT(DelTag(typed_task));
      break;
    }
    case Method::kRenameTag: {
      auto& typed_task = task_ptr.template Cast<RenameTagTask>();
      CLIO_CO_AWAIT(RenameTag(typed_task));
      break;
    }
    case Method::kGetOrCreateTagAlias: {
      auto& typed_task = task_ptr.template Cast<GetOrCreateTagAliasTask>();
      CLIO_CO_AWAIT(GetOrCreateTagAlias(typed_task));
      break;
    }
    case Method::kGetTagName: {
      auto& typed_task = task_ptr.template Cast<GetTagNameTask>();
      CLIO_CO_AWAIT(GetTagName(typed_task));
      break;
    }
    case Method::kGetTagSize: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<GetTagSizeTask>();
      CLIO_CO_AWAIT(GetTagSize(typed_task));
      break;
    }
    case Method::kGetCapacity: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<GetCapacityTask>();
      CLIO_CO_AWAIT(GetCapacity(typed_task));
      break;
    }
    case Method::kGetNumAliases: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<GetNumAliasesTask>();
      CLIO_CO_AWAIT(GetNumAliases(typed_task));
      break;
    }
    case Method::kPollTelemetryLog: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<PollTelemetryLogTask>();
      CLIO_CO_AWAIT(PollTelemetryLog(typed_task));
      break;
    }
    case Method::kGetBlobScore: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<GetBlobScoreTask>();
      CLIO_CO_AWAIT(GetBlobScore(typed_task));
      break;
    }
    case Method::kGetBlobSize: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<GetBlobSizeTask>();
      CLIO_CO_AWAIT(GetBlobSize(typed_task));
      break;
    }
    case Method::kGetContainedBlobs: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<GetContainedBlobsTask>();
      CLIO_CO_AWAIT(GetContainedBlobs(typed_task));
      break;
    }
    case Method::kGetBlobInfo: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<GetBlobInfoTask>();
      CLIO_CO_AWAIT(GetBlobInfo(typed_task));
      break;
    }
    case Method::kTagQuery: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<TagQueryTask>();
      CLIO_CO_AWAIT(TagQuery(typed_task));
      break;
    }
    case Method::kBlobQuery: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<BlobQueryTask>();
      CLIO_CO_AWAIT(BlobQuery(typed_task));
      break;
    }
    case Method::kGetTargetInfo: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<GetTargetInfoTask>();
      CLIO_CO_AWAIT(GetTargetInfo(typed_task));
      break;
    }
    case Method::kFlushMetadata: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<FlushMetadataTask>();
      CLIO_CO_AWAIT(FlushMetadata(typed_task));
      break;
    }
    case Method::kFlushData: {
      // Cast task FullPtr to specific type
      auto& typed_task = task_ptr.template Cast<FlushDataTask>();
      CLIO_CO_AWAIT(FlushData(typed_task));
      break;
    }
    case Method::kSemanticSearch: {
      auto& typed_task = task_ptr.template Cast<SemanticSearchTask>();
      CLIO_CO_AWAIT(SemanticSearch(typed_task));
      break;
    }
    case Method::kTemporalSearch: {
      auto& typed_task = task_ptr.template Cast<TemporalSearchTask>();
      CLIO_CO_AWAIT(TemporalSearch(typed_task));
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
  CLIO_CO_RETURN;
  CLIO_TASK_BODY_END
}

void Runtime::SaveTask(clio::run::u32 method, clio::run::SaveTaskArchive& archive, 
                        clio::run::shared_ptr<clio::run::Task>& task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      archive << *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      archive << *typed_task;
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      archive << *typed_task;
      break;
    }
    case Method::kRegisterTarget: {
      auto& typed_task = task_ptr.template Cast<RegisterTargetTask>();
      archive << *typed_task;
      break;
    }
    case Method::kUnregisterTarget: {
      auto& typed_task = task_ptr.template Cast<UnregisterTargetTask>();
      archive << *typed_task;
      break;
    }
    case Method::kListTargets: {
      auto& typed_task = task_ptr.template Cast<ListTargetsTask>();
      archive << *typed_task;
      break;
    }
    case Method::kStatTargets: {
      auto& typed_task = task_ptr.template Cast<StatTargetsTask>();
      archive << *typed_task;
      break;
    }
    case Method::kGetOrCreateTag: {
      auto& typed_task = task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      archive << *typed_task;
      break;
    }
    case Method::kPutBlob: {
      auto& typed_task = task_ptr.template Cast<PutBlobTask>();
      archive << *typed_task;
      break;
    }
    case Method::kGetBlob: {
      auto& typed_task = task_ptr.template Cast<GetBlobTask>();
      archive << *typed_task;
      break;
    }
    case Method::kReorganizeBlob: {
      auto& typed_task = task_ptr.template Cast<ReorganizeBlobTask>();
      archive << *typed_task;
      break;
    }
    case Method::kPodPutBlob: {
      auto& typed_task = task_ptr.template Cast<PodPutBlobTask>();
      archive << *typed_task;
      break;
    }
    case Method::kPodGetBlob: {
      auto& typed_task = task_ptr.template Cast<PodGetBlobTask>();
      archive << *typed_task;
      break;
    }
    case Method::kPodReorganizeBlob: {
      auto& typed_task = task_ptr.template Cast<PodReorganizeBlobTask>();
      archive << *typed_task;
      break;
    }
    case Method::kDynamicReorganize: {
      auto& typed_task = task_ptr.template Cast<DynamicReorganizeTask>();
      archive << *typed_task;
      break;
    }
    case Method::kDelBlob: {
      auto& typed_task = task_ptr.template Cast<DelBlobTask>();
      archive << *typed_task;
      break;
    }
    case Method::kTruncateBlob: {
      auto& typed_task = task_ptr.template Cast<TruncateBlobTask>();
      archive << *typed_task;
      break;
    }
    case Method::kDelTag: {
      auto& typed_task = task_ptr.template Cast<DelTagTask>();
      archive << *typed_task;
      break;
    }
    case Method::kRenameTag: {
      auto& typed_task = task_ptr.template Cast<RenameTagTask>();
      archive << *typed_task;
      break;
    }
    case Method::kGetOrCreateTagAlias: {
      auto& typed_task = task_ptr.template Cast<GetOrCreateTagAliasTask>();
      archive << *typed_task;
      break;
    }
    case Method::kGetTagName: {
      auto& typed_task = task_ptr.template Cast<GetTagNameTask>();
      archive << *typed_task;
      break;
    }
    case Method::kGetTagSize: {
      auto& typed_task = task_ptr.template Cast<GetTagSizeTask>();
      archive << *typed_task;
      break;
    }
    case Method::kGetCapacity: {
      auto& typed_task = task_ptr.template Cast<GetCapacityTask>();
      archive << *typed_task;
      break;
    }
    case Method::kGetNumAliases: {
      auto& typed_task = task_ptr.template Cast<GetNumAliasesTask>();
      archive << *typed_task;
      break;
    }
    case Method::kPollTelemetryLog: {
      auto& typed_task = task_ptr.template Cast<PollTelemetryLogTask>();
      archive << *typed_task;
      break;
    }
    case Method::kGetBlobScore: {
      auto& typed_task = task_ptr.template Cast<GetBlobScoreTask>();
      archive << *typed_task;
      break;
    }
    case Method::kGetBlobSize: {
      auto& typed_task = task_ptr.template Cast<GetBlobSizeTask>();
      archive << *typed_task;
      break;
    }
    case Method::kGetContainedBlobs: {
      auto& typed_task = task_ptr.template Cast<GetContainedBlobsTask>();
      archive << *typed_task;
      break;
    }
    case Method::kGetBlobInfo: {
      auto& typed_task = task_ptr.template Cast<GetBlobInfoTask>();
      archive << *typed_task;
      break;
    }
    case Method::kTagQuery: {
      auto& typed_task = task_ptr.template Cast<TagQueryTask>();
      archive << *typed_task;
      break;
    }
    case Method::kBlobQuery: {
      auto& typed_task = task_ptr.template Cast<BlobQueryTask>();
      archive << *typed_task;
      break;
    }
    case Method::kGetTargetInfo: {
      auto& typed_task = task_ptr.template Cast<GetTargetInfoTask>();
      archive << *typed_task;
      break;
    }
    case Method::kFlushMetadata: {
      auto& typed_task = task_ptr.template Cast<FlushMetadataTask>();
      archive << *typed_task;
      break;
    }
    case Method::kFlushData: {
      auto& typed_task = task_ptr.template Cast<FlushDataTask>();
      archive << *typed_task;
      break;
    }
    case Method::kSemanticSearch: {
      auto& typed_task = task_ptr.template Cast<SemanticSearchTask>();
      archive << *typed_task;
      break;
    }
    case Method::kTemporalSearch: {
      auto& typed_task = task_ptr.template Cast<TemporalSearchTask>();
      archive << *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadTask(clio::run::u32 method, clio::run::LoadTaskArchive& archive,
                        clio::run::shared_ptr<clio::run::Task>& task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kRegisterTarget: {
      auto& typed_task = task_ptr.template Cast<RegisterTargetTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kUnregisterTarget: {
      auto& typed_task = task_ptr.template Cast<UnregisterTargetTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kListTargets: {
      auto& typed_task = task_ptr.template Cast<ListTargetsTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kStatTargets: {
      auto& typed_task = task_ptr.template Cast<StatTargetsTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kGetOrCreateTag: {
      auto& typed_task = task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      archive >> *typed_task;
      break;
    }
    case Method::kPutBlob: {
      auto& typed_task = task_ptr.template Cast<PutBlobTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kGetBlob: {
      auto& typed_task = task_ptr.template Cast<GetBlobTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kReorganizeBlob: {
      auto& typed_task = task_ptr.template Cast<ReorganizeBlobTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kPodPutBlob: {
      auto& typed_task = task_ptr.template Cast<PodPutBlobTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kPodGetBlob: {
      auto& typed_task = task_ptr.template Cast<PodGetBlobTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kPodReorganizeBlob: {
      auto& typed_task = task_ptr.template Cast<PodReorganizeBlobTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kDynamicReorganize: {
      auto& typed_task = task_ptr.template Cast<DynamicReorganizeTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kDelBlob: {
      auto& typed_task = task_ptr.template Cast<DelBlobTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kTruncateBlob: {
      auto& typed_task = task_ptr.template Cast<TruncateBlobTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kDelTag: {
      auto& typed_task = task_ptr.template Cast<DelTagTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kRenameTag: {
      auto& typed_task = task_ptr.template Cast<RenameTagTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kGetOrCreateTagAlias: {
      auto& typed_task = task_ptr.template Cast<GetOrCreateTagAliasTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kGetTagName: {
      auto& typed_task = task_ptr.template Cast<GetTagNameTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kGetTagSize: {
      auto& typed_task = task_ptr.template Cast<GetTagSizeTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kGetCapacity: {
      auto& typed_task = task_ptr.template Cast<GetCapacityTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kGetNumAliases: {
      auto& typed_task = task_ptr.template Cast<GetNumAliasesTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kPollTelemetryLog: {
      auto& typed_task = task_ptr.template Cast<PollTelemetryLogTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kGetBlobScore: {
      auto& typed_task = task_ptr.template Cast<GetBlobScoreTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kGetBlobSize: {
      auto& typed_task = task_ptr.template Cast<GetBlobSizeTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kGetContainedBlobs: {
      auto& typed_task = task_ptr.template Cast<GetContainedBlobsTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kGetBlobInfo: {
      auto& typed_task = task_ptr.template Cast<GetBlobInfoTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kTagQuery: {
      auto& typed_task = task_ptr.template Cast<TagQueryTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kBlobQuery: {
      auto& typed_task = task_ptr.template Cast<BlobQueryTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kGetTargetInfo: {
      auto& typed_task = task_ptr.template Cast<GetTargetInfoTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kFlushMetadata: {
      auto& typed_task = task_ptr.template Cast<FlushMetadataTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kFlushData: {
      auto& typed_task = task_ptr.template Cast<FlushDataTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kSemanticSearch: {
      auto& typed_task = task_ptr.template Cast<SemanticSearchTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kTemporalSearch: {
      auto& typed_task = task_ptr.template Cast<TemporalSearchTask>();
      archive >> *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

clio::run::shared_ptr<clio::run::Task> Runtime::AllocLoadTask(clio::run::u32 method, clio::run::LoadTaskArchive& archive) {
  clio::run::shared_ptr<clio::run::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalLoadTask(clio::run::u32 method, clio::run::DefaultLoadArchive& archive,
                            clio::run::shared_ptr<clio::run::Task>& task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kRegisterTarget: {
      auto& typed_task = task_ptr.template Cast<RegisterTargetTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kUnregisterTarget: {
      auto& typed_task = task_ptr.template Cast<UnregisterTargetTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kListTargets: {
      auto& typed_task = task_ptr.template Cast<ListTargetsTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kStatTargets: {
      auto& typed_task = task_ptr.template Cast<StatTargetsTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kGetOrCreateTag: {
      auto& typed_task = task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kPutBlob: {
      auto& typed_task = task_ptr.template Cast<PutBlobTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kGetBlob: {
      auto& typed_task = task_ptr.template Cast<GetBlobTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kReorganizeBlob: {
      auto& typed_task = task_ptr.template Cast<ReorganizeBlobTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kPodPutBlob: {
      auto& typed_task = task_ptr.template Cast<PodPutBlobTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kPodGetBlob: {
      auto& typed_task = task_ptr.template Cast<PodGetBlobTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kPodReorganizeBlob: {
      auto& typed_task = task_ptr.template Cast<PodReorganizeBlobTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kDynamicReorganize: {
      auto& typed_task = task_ptr.template Cast<DynamicReorganizeTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kDelBlob: {
      auto& typed_task = task_ptr.template Cast<DelBlobTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kTruncateBlob: {
      auto& typed_task = task_ptr.template Cast<TruncateBlobTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kDelTag: {
      auto& typed_task = task_ptr.template Cast<DelTagTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kRenameTag: {
      auto& typed_task = task_ptr.template Cast<RenameTagTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kGetOrCreateTagAlias: {
      auto& typed_task = task_ptr.template Cast<GetOrCreateTagAliasTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kGetTagName: {
      auto& typed_task = task_ptr.template Cast<GetTagNameTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kGetTagSize: {
      auto& typed_task = task_ptr.template Cast<GetTagSizeTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kGetCapacity: {
      auto& typed_task = task_ptr.template Cast<GetCapacityTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kGetNumAliases: {
      auto& typed_task = task_ptr.template Cast<GetNumAliasesTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kPollTelemetryLog: {
      auto& typed_task = task_ptr.template Cast<PollTelemetryLogTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kGetBlobScore: {
      auto& typed_task = task_ptr.template Cast<GetBlobScoreTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kGetBlobSize: {
      auto& typed_task = task_ptr.template Cast<GetBlobSizeTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kGetContainedBlobs: {
      auto& typed_task = task_ptr.template Cast<GetContainedBlobsTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kGetBlobInfo: {
      auto& typed_task = task_ptr.template Cast<GetBlobInfoTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kTagQuery: {
      auto& typed_task = task_ptr.template Cast<TagQueryTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kBlobQuery: {
      auto& typed_task = task_ptr.template Cast<BlobQueryTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kGetTargetInfo: {
      auto& typed_task = task_ptr.template Cast<GetTargetInfoTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kFlushMetadata: {
      auto& typed_task = task_ptr.template Cast<FlushMetadataTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kFlushData: {
      auto& typed_task = task_ptr.template Cast<FlushDataTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kSemanticSearch: {
      auto& typed_task = task_ptr.template Cast<SemanticSearchTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kTemporalSearch: {
      auto& typed_task = task_ptr.template Cast<TemporalSearchTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

clio::run::shared_ptr<clio::run::Task> Runtime::LocalAllocLoadTask(clio::run::u32 method, clio::run::DefaultLoadArchive& archive) {
  clio::run::shared_ptr<clio::run::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LocalLoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalSaveTask(clio::run::u32 method, clio::run::DefaultSaveArchive& archive, 
                             clio::run::shared_ptr<clio::run::Task>& task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kRegisterTarget: {
      auto& typed_task = task_ptr.template Cast<RegisterTargetTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kUnregisterTarget: {
      auto& typed_task = task_ptr.template Cast<UnregisterTargetTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kListTargets: {
      auto& typed_task = task_ptr.template Cast<ListTargetsTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kStatTargets: {
      auto& typed_task = task_ptr.template Cast<StatTargetsTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kGetOrCreateTag: {
      auto& typed_task = task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kPutBlob: {
      auto& typed_task = task_ptr.template Cast<PutBlobTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kGetBlob: {
      auto& typed_task = task_ptr.template Cast<GetBlobTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kReorganizeBlob: {
      auto& typed_task = task_ptr.template Cast<ReorganizeBlobTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kPodPutBlob: {
      auto& typed_task = task_ptr.template Cast<PodPutBlobTask>();
      archive << *typed_task;
      break;
    }
    case Method::kPodGetBlob: {
      auto& typed_task = task_ptr.template Cast<PodGetBlobTask>();
      archive << *typed_task;
      break;
    }
    case Method::kPodReorganizeBlob: {
      auto& typed_task = task_ptr.template Cast<PodReorganizeBlobTask>();
      archive << *typed_task;
      break;
    }
    case Method::kDynamicReorganize: {
      auto& typed_task = task_ptr.template Cast<DynamicReorganizeTask>();
      archive << *typed_task;
      break;
    }
    case Method::kDelBlob: {
      auto& typed_task = task_ptr.template Cast<DelBlobTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kTruncateBlob: {
      auto& typed_task = task_ptr.template Cast<TruncateBlobTask>();
      archive << *typed_task;
      break;
    }
    case Method::kDelTag: {
      auto& typed_task = task_ptr.template Cast<DelTagTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kRenameTag: {
      auto& typed_task = task_ptr.template Cast<RenameTagTask>();
      archive << *typed_task;
      break;
    }
    case Method::kGetOrCreateTagAlias: {
      auto& typed_task = task_ptr.template Cast<GetOrCreateTagAliasTask>();
      archive << *typed_task;
      break;
    }
    case Method::kGetTagName: {
      auto& typed_task = task_ptr.template Cast<GetTagNameTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kGetTagSize: {
      auto& typed_task = task_ptr.template Cast<GetTagSizeTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kGetCapacity: {
      auto& typed_task = task_ptr.template Cast<GetCapacityTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kGetNumAliases: {
      auto& typed_task = task_ptr.template Cast<GetNumAliasesTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kPollTelemetryLog: {
      auto& typed_task = task_ptr.template Cast<PollTelemetryLogTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kGetBlobScore: {
      auto& typed_task = task_ptr.template Cast<GetBlobScoreTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kGetBlobSize: {
      auto& typed_task = task_ptr.template Cast<GetBlobSizeTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kGetContainedBlobs: {
      auto& typed_task = task_ptr.template Cast<GetContainedBlobsTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kGetBlobInfo: {
      auto& typed_task = task_ptr.template Cast<GetBlobInfoTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kTagQuery: {
      auto& typed_task = task_ptr.template Cast<TagQueryTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kBlobQuery: {
      auto& typed_task = task_ptr.template Cast<BlobQueryTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kGetTargetInfo: {
      auto& typed_task = task_ptr.template Cast<GetTargetInfoTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kFlushMetadata: {
      auto& typed_task = task_ptr.template Cast<FlushMetadataTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kFlushData: {
      auto& typed_task = task_ptr.template Cast<FlushDataTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kSemanticSearch: {
      auto& typed_task = task_ptr.template Cast<SemanticSearchTask>();
      archive << *typed_task;
      break;
    }
    case Method::kTemporalSearch: {
      auto& typed_task = task_ptr.template Cast<TemporalSearchTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

clio::run::shared_ptr<clio::run::Task> Runtime::NewCopyTask(clio::run::u32 method, clio::run::shared_ptr<clio::run::Task>& orig_task_ptr, bool deep) {
  auto* ipc_manager = CLIO_IPC;
  if (!ipc_manager) {
    return clio::run::shared_ptr<clio::run::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<CreateTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<CreateTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kDestroy: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<DestroyTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<DestroyTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kMonitor: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<MonitorTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<MonitorTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kRegisterTarget: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<RegisterTargetTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<RegisterTargetTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<RegisterTargetTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kUnregisterTarget: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<UnregisterTargetTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<UnregisterTargetTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<UnregisterTargetTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kListTargets: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ListTargetsTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<ListTargetsTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<ListTargetsTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kStatTargets: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<StatTargetsTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<StatTargetsTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<StatTargetsTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kGetOrCreateTag: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<core::GetOrCreateTagTask<core::CreateParams>>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<core::GetOrCreateTagTask<core::CreateParams>>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kPutBlob: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<PutBlobTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<PutBlobTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<PutBlobTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kGetBlob: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GetBlobTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<GetBlobTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<GetBlobTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kReorganizeBlob: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ReorganizeBlobTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<ReorganizeBlobTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<ReorganizeBlobTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kPodPutBlob: {
      auto new_task_ptr = ipc_manager->NewTask<PodPutBlobTask>();
      if (!new_task_ptr.IsNull()) {
        auto& task_typed = orig_task_ptr.template Cast<PodPutBlobTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<PodPutBlobTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kPodGetBlob: {
      auto new_task_ptr = ipc_manager->NewTask<PodGetBlobTask>();
      if (!new_task_ptr.IsNull()) {
        auto& task_typed = orig_task_ptr.template Cast<PodGetBlobTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<PodGetBlobTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kPodReorganizeBlob: {
      auto new_task_ptr = ipc_manager->NewTask<PodReorganizeBlobTask>();
      if (!new_task_ptr.IsNull()) {
        auto& task_typed = orig_task_ptr.template Cast<PodReorganizeBlobTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<PodReorganizeBlobTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kDynamicReorganize: {
      auto new_task_ptr = ipc_manager->NewTask<DynamicReorganizeTask>();
      if (!new_task_ptr.IsNull()) {
        auto& task_typed = orig_task_ptr.template Cast<DynamicReorganizeTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<DynamicReorganizeTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kDelBlob: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DelBlobTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<DelBlobTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<DelBlobTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kTruncateBlob: {
      auto new_task_ptr = ipc_manager->NewTask<TruncateBlobTask>();
      if (!new_task_ptr.IsNull()) {
        auto& task_typed = orig_task_ptr.template Cast<TruncateBlobTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<TruncateBlobTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kRenameTag: {
      auto new_task_ptr = ipc_manager->NewTask<RenameTagTask>();
      if (!new_task_ptr.IsNull()) {
        auto& task_typed = orig_task_ptr.template Cast<RenameTagTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<RenameTagTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kGetOrCreateTagAlias: {
      auto new_task_ptr = ipc_manager->NewTask<GetOrCreateTagAliasTask>();
      if (!new_task_ptr.IsNull()) {
        auto& task_typed = orig_task_ptr.template Cast<GetOrCreateTagAliasTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<GetOrCreateTagAliasTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kDelTag: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DelTagTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<DelTagTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<DelTagTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kGetTagName: {
      auto new_task_ptr = ipc_manager->NewTask<GetTagNameTask>();
      if (!new_task_ptr.IsNull()) {
        auto& task_typed = orig_task_ptr.template Cast<GetTagNameTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<GetTagNameTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kGetTagSize: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GetTagSizeTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<GetTagSizeTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<GetTagSizeTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kGetCapacity: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GetCapacityTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<GetCapacityTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<GetCapacityTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kGetNumAliases: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GetNumAliasesTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<GetNumAliasesTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<GetNumAliasesTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kPollTelemetryLog: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<PollTelemetryLogTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<PollTelemetryLogTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<PollTelemetryLogTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kGetBlobScore: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GetBlobScoreTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<GetBlobScoreTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<GetBlobScoreTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kGetBlobSize: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GetBlobSizeTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<GetBlobSizeTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<GetBlobSizeTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kGetContainedBlobs: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GetContainedBlobsTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<GetContainedBlobsTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<GetContainedBlobsTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kGetBlobInfo: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GetBlobInfoTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<GetBlobInfoTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<GetBlobInfoTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kTagQuery: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<TagQueryTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<TagQueryTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<TagQueryTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kBlobQuery: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<BlobQueryTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<BlobQueryTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<BlobQueryTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kGetTargetInfo: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GetTargetInfoTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<GetTargetInfoTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<GetTargetInfoTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kFlushMetadata: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<FlushMetadataTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<FlushMetadataTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<FlushMetadataTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kFlushData: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<FlushDataTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<FlushDataTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<FlushDataTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kSemanticSearch: {
      auto new_task_ptr = ipc_manager->NewTask<SemanticSearchTask>();
      if (!new_task_ptr.IsNull()) {
        auto& task_typed = orig_task_ptr.template Cast<SemanticSearchTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<SemanticSearchTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kTemporalSearch: {
      auto new_task_ptr = ipc_manager->NewTask<TemporalSearchTask>();
      if (!new_task_ptr.IsNull()) {
        auto& task_typed = orig_task_ptr.template Cast<TemporalSearchTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<TemporalSearchTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    default: {
      // For unknown methods, create base Task copy
      auto new_task_ptr = ipc_manager->NewTask<clio::run::Task>();
      if (!new_task_ptr.IsNull()) {
        new_task_ptr->Copy(ctp::ipc::FullPtr<clio::run::Task>(orig_task_ptr.get()));
        return new_task_ptr;
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
  return clio::run::shared_ptr<clio::run::Task>();
}

clio::run::shared_ptr<clio::run::Task> Runtime::NewTask(clio::run::u32 method) {
  auto* ipc_manager = CLIO_IPC;
  if (!ipc_manager) {
    return clio::run::shared_ptr<clio::run::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kDestroy: {
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kMonitor: {
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kRegisterTarget: {
      auto new_task_ptr = ipc_manager->NewTask<RegisterTargetTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kUnregisterTarget: {
      auto new_task_ptr = ipc_manager->NewTask<UnregisterTargetTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kListTargets: {
      auto new_task_ptr = ipc_manager->NewTask<ListTargetsTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kStatTargets: {
      auto new_task_ptr = ipc_manager->NewTask<StatTargetsTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kGetOrCreateTag: {
      auto new_task_ptr = ipc_manager->NewTask<core::GetOrCreateTagTask<core::CreateParams>>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kPutBlob: {
      auto new_task_ptr = ipc_manager->NewTask<PutBlobTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kGetBlob: {
      auto new_task_ptr = ipc_manager->NewTask<GetBlobTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kReorganizeBlob: {
      auto new_task_ptr = ipc_manager->NewTask<ReorganizeBlobTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kPodPutBlob: {
      auto new_task_ptr = ipc_manager->NewTask<PodPutBlobTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kPodGetBlob: {
      auto new_task_ptr = ipc_manager->NewTask<PodGetBlobTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kPodReorganizeBlob: {
      auto new_task_ptr = ipc_manager->NewTask<PodReorganizeBlobTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kDynamicReorganize: {
      auto new_task_ptr = ipc_manager->NewTask<DynamicReorganizeTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kDelBlob: {
      auto new_task_ptr = ipc_manager->NewTask<DelBlobTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kTruncateBlob: {
      auto new_task_ptr = ipc_manager->NewTask<TruncateBlobTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kDelTag: {
      auto new_task_ptr = ipc_manager->NewTask<DelTagTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kRenameTag: {
      auto new_task_ptr = ipc_manager->NewTask<RenameTagTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kGetOrCreateTagAlias: {
      auto new_task_ptr = ipc_manager->NewTask<GetOrCreateTagAliasTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kGetTagName: {
      auto new_task_ptr = ipc_manager->NewTask<GetTagNameTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kGetTagSize: {
      auto new_task_ptr = ipc_manager->NewTask<GetTagSizeTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kGetCapacity: {
      auto new_task_ptr = ipc_manager->NewTask<GetCapacityTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kGetNumAliases: {
      auto new_task_ptr = ipc_manager->NewTask<GetNumAliasesTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kPollTelemetryLog: {
      auto new_task_ptr = ipc_manager->NewTask<PollTelemetryLogTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kGetBlobScore: {
      auto new_task_ptr = ipc_manager->NewTask<GetBlobScoreTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kGetBlobSize: {
      auto new_task_ptr = ipc_manager->NewTask<GetBlobSizeTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kGetContainedBlobs: {
      auto new_task_ptr = ipc_manager->NewTask<GetContainedBlobsTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kGetBlobInfo: {
      auto new_task_ptr = ipc_manager->NewTask<GetBlobInfoTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kTagQuery: {
      auto new_task_ptr = ipc_manager->NewTask<TagQueryTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kBlobQuery: {
      auto new_task_ptr = ipc_manager->NewTask<BlobQueryTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kGetTargetInfo: {
      auto new_task_ptr = ipc_manager->NewTask<GetTargetInfoTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kFlushMetadata: {
      auto new_task_ptr = ipc_manager->NewTask<FlushMetadataTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kFlushData: {
      auto new_task_ptr = ipc_manager->NewTask<FlushDataTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kSemanticSearch: {
      auto new_task_ptr = ipc_manager->NewTask<SemanticSearchTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kTemporalSearch: {
      auto new_task_ptr = ipc_manager->NewTask<TemporalSearchTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    default: {
      // For unknown methods, return null pointer
      return clio::run::shared_ptr<clio::run::Task>();
    }
  }
}

void Runtime::AggregateOut(clio::run::u32 method, clio::run::shared_ptr<clio::run::Task>& orig_task,
                        const clio::run::shared_ptr<clio::run::Task>& replica_task) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = orig_task.template Cast<CreateTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = orig_task.template Cast<DestroyTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = orig_task.template Cast<MonitorTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kRegisterTarget: {
      auto& typed_task = orig_task.template Cast<RegisterTargetTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kUnregisterTarget: {
      auto& typed_task = orig_task.template Cast<UnregisterTargetTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kListTargets: {
      auto& typed_task = orig_task.template Cast<ListTargetsTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kStatTargets: {
      auto& typed_task = orig_task.template Cast<StatTargetsTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kGetOrCreateTag: {
      auto& typed_task = orig_task.template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kPutBlob: {
      auto& typed_task = orig_task.template Cast<PutBlobTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kGetBlob: {
      auto& typed_task = orig_task.template Cast<GetBlobTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kReorganizeBlob: {
      auto& typed_task = orig_task.template Cast<ReorganizeBlobTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kPodPutBlob: {
      auto& typed_task = orig_task.template Cast<PodPutBlobTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kPodGetBlob: {
      auto& typed_task = orig_task.template Cast<PodGetBlobTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kPodReorganizeBlob: {
      auto& typed_task = orig_task.template Cast<PodReorganizeBlobTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kDynamicReorganize: {
      auto& typed_task = orig_task.template Cast<DynamicReorganizeTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kDelBlob: {
      auto& typed_task = orig_task.template Cast<DelBlobTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kTruncateBlob: {
      auto& typed_task = orig_task.template Cast<TruncateBlobTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kDelTag: {
      auto& typed_task = orig_task.template Cast<DelTagTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kRenameTag: {
      auto& typed_task = orig_task.template Cast<RenameTagTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kGetOrCreateTagAlias: {
      auto& typed_task = orig_task.template Cast<GetOrCreateTagAliasTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kGetTagName: {
      auto& typed_task = orig_task.template Cast<GetTagNameTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kGetTagSize: {
      auto& typed_task = orig_task.template Cast<GetTagSizeTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kGetCapacity: {
      auto& typed_task = orig_task.template Cast<GetCapacityTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kGetNumAliases: {
      auto& typed_task = orig_task.template Cast<GetNumAliasesTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kPollTelemetryLog: {
      auto& typed_task = orig_task.template Cast<PollTelemetryLogTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kGetBlobScore: {
      auto& typed_task = orig_task.template Cast<GetBlobScoreTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kGetBlobSize: {
      auto& typed_task = orig_task.template Cast<GetBlobSizeTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kGetContainedBlobs: {
      auto& typed_task = orig_task.template Cast<GetContainedBlobsTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kGetBlobInfo: {
      auto& typed_task = orig_task.template Cast<GetBlobInfoTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kTagQuery: {
      auto& typed_task = orig_task.template Cast<TagQueryTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kBlobQuery: {
      auto& typed_task = orig_task.template Cast<BlobQueryTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kGetTargetInfo: {
      auto& typed_task = orig_task.template Cast<GetTargetInfoTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kFlushMetadata: {
      auto& typed_task = orig_task.template Cast<FlushMetadataTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kFlushData: {
      auto& typed_task = orig_task.template Cast<FlushDataTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kSemanticSearch: {
      auto& typed_task = orig_task.template Cast<SemanticSearchTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kTemporalSearch: {
      auto& typed_task = orig_task.template Cast<TemporalSearchTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    default: {
      orig_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
  }
}


} // namespace clio::cte::core
