/*
 * Copyright (c) 2024, Gnosis Research Center, Illinois Institute of Technology
 * All rights reserved.
 * This file is part of IOWarp Core.
 * See COPYING file in the top-level directory.
 */

#ifndef CHIMAERA_BDEV_GPU_RUNTIME_H_
#define CHIMAERA_BDEV_GPU_RUNTIME_H_

#include "chimaera/gpu/container.h"
#include "chimaera/bdev/bdev_tasks.h"
#include "chimaera/bdev/autogen/bdev_methods.h"

namespace chimaera::bdev {

/** GPU block size categories: 4KB, 64KB, 128KB, 1MB */
enum class GpuBlockSizeCategory : chi::u32 {
  k4KB = 0,
  k64KB = 1,
  k128KB = 2,
  k1MB = 3,
  kNumCategories = 4
};

/** Block sizes in bytes for each GPU category.
 *  HSHM_GPU_VAR expands to __device__ on CUDA/ROCm and to nothing on SYCL,
 *  so this constexpr array is reachable from both backends. */
HSHM_GPU_VAR static constexpr chi::u64 kGpuBlockSizes[] = {
    4096,       // 4KB
    65536,      // 64KB
    131072,     // 128KB
    1048576     // 1MB
};

/** Per-warp free list for a single size category (simple stack) */
struct GpuFreeList {
  static constexpr chi::u32 kMaxFreeBlocks = 64;
  Block blocks_[kMaxFreeBlocks];
  chi::u32 count_;

  HSHM_GPU_FUN GpuFreeList() : count_(0) {}

  HSHM_GPU_FUN bool Push(const Block &blk) {
    if (count_ >= kMaxFreeBlocks) return false;
    blocks_[count_++] = blk;
    return true;
  }

  HSHM_GPU_FUN bool Pop(Block &blk) {
    if (count_ == 0) return false;
    blk = blocks_[--count_];
    return true;
  }

  HSHM_GPU_FUN bool Empty() const { return count_ == 0; }
};

/** Per-warp block cache: one free list per size category */
struct GpuWarpBlockCache {
  static constexpr chi::u32 kNumCategories =
      static_cast<chi::u32>(GpuBlockSizeCategory::kNumCategories);
  GpuFreeList lists_[kNumCategories];
};

/**
 * GPU-side container for the bdev module.
 *
 * Handles kUpdate, kAllocateBlocks, kFreeBlocks, kWrite, and kRead
 * directly on the GPU using device or pinned memory.
 *
 * Initialized by an UpdateTask submitted from the CPU bdev runtime's
 * Create() handler after allocating kHbm or kPinned memory.
 */
class GpuRuntime : public chi::gpu::Container {
 public:
  chi::u64 hbm_ptr_ = 0;
  chi::u64 pinned_ptr_ = 0;
  chi::u64 hbm_size_ = 0;
  chi::u64 pinned_size_ = 0;
  chi::u64 total_size_ = 0;
  chi::u32 bdev_type_ = 0;
  chi::u32 alignment_ = 4096;
  chi::u32 num_warps_ = 0;
  chi::u64 gpu_heap_ = 0;
  chi::priv::shared_vector<GpuWarpBlockCache> warp_caches_{CHI_PRIV_SHARED_ALLOC};

  // Constructor is autogenerated (sets function pointer table)
  ~GpuRuntime() = default;

  /** Find the smallest size category that fits the requested size */
  HSHM_GPU_FUN static int FindSizeCategory(chi::u64 size) {
    for (int i = 0; i < static_cast<int>(GpuBlockSizeCategory::kNumCategories); ++i) {
      if (kGpuBlockSizes[i] >= size) return i;
    }
    return -1;  // larger than any cached size
  }

  // HSHM_DEVICE_EXTERN tags these as cross-TU device functions: their
  // bodies live in bdev_runtime_gpu.cc. Required by SYCL_EXTERNAL on DPC++;
  // a no-op on CUDA/ROCm (separable compilation handles cross-TU device
  // linkage).
  HSHM_DEVICE_EXTERN HSHM_GPU_FUN void Update(
      hipc::FullPtr<UpdateTask> task, chi::gpu::RunContext &rctx);

  HSHM_DEVICE_EXTERN HSHM_GPU_FUN void AllocateBlocks(
      hipc::FullPtr<AllocateBlocksTask> task, chi::gpu::RunContext &rctx);

  HSHM_DEVICE_EXTERN HSHM_GPU_FUN void FreeBlocks(
      hipc::FullPtr<FreeBlocksTask> task, chi::gpu::RunContext &rctx);

  HSHM_DEVICE_EXTERN HSHM_GPU_FUN void Write(
      hipc::FullPtr<WriteTask> task, chi::gpu::RunContext &rctx);

  HSHM_DEVICE_EXTERN HSHM_GPU_FUN void Read(
      hipc::FullPtr<ReadTask> task, chi::gpu::RunContext &rctx);

  HSHM_GPU_FUN chi::TaskStat GetTaskStats(chi::u32 method_id) const {
    chi::TaskStat stat;
    (void)method_id;
    return stat;
  }

  // Autogenerated virtual method overrides (switch-case dispatch)
  #include "autogen/bdev_gpu_lib_exec.h"
};

}  // namespace chimaera::bdev

#endif  // CHIMAERA_BDEV_GPU_RUNTIME_H_
