/*
 * Copyright (c) 2024, Gnosis Research Center, Illinois Institute of Technology
 * All rights reserved.
 *
 * This file is part of IOWarp Core.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef CHIMAERA_INCLUDE_CHIMAERA_GPU_CONTAINER_H_
#define CHIMAERA_INCLUDE_CHIMAERA_GPU_CONTAINER_H_

#include "chimaera/types.h"
#include "chimaera/pool_query.h"
#include "chimaera/task.h"
#include "chimaera/local_task_archives.h"
// Pull in chi::gpu::IpcManager's full definition so chimod _gpu_runtime.h
// files (which include this) can call CHI_IPC->NewTask<...> from the
// autogen-emitted dispatch table without separate forward declarations.
#include "chimaera/gpu/gpu_ipc_manager.h"

namespace chi {
namespace gpu {

/** Unsigned 32-bit integer */
using u32 = uint32_t;

static constexpr u32 kWarpSize = 32;

// Forward declaration
class Container;

/**
 * GPU-side execution context for task methods dispatched via CDP.
 *
 * One RunContext is created per child kernel launch, typically as a
 * stack-local variable.  Contains the dispatch metadata needed by
 * container methods: which container, which method, and the task pointer.
 */
struct RunContext {
  /** GPU container that owns the method being executed */
  Container *container_;
  /** Method ID to dispatch */
  u32 method_id_;
  /** Full pointer to the task being executed */
  hipc::FullPtr<chi::Task> task_ptr_;
  /** FutureShm associated with this task (for completion signaling) */
  gpu::FutureShm *task_fshm_;
  /** Total thread parallelism for this task (gridDim.x * blockDim.x) */
  u32 parallelism_;
  /** IpcManager pointer for cross-function CHI_IPC resolution under SYCL.
   *  Set by the worker before dispatch; chimod methods reach it via
   *  rctx.ipc_mgr_ (which the SYCL CHI_IPC macro picks up via name
   *  lookup when the method body opens with `auto *g_ipc_manager_ptr =
   *  rctx.ipc_mgr_;`). Always nullptr on CUDA/ROCm where __shared__ +
   *  GetBlockIpcManager handles per-block resolution. */
  IpcManager *ipc_mgr_ = nullptr;
};

/**
 * GPU-side container base class.
 *
 * Uses an inline function pointer table instead of virtual dispatch.
 * This eliminates one global memory dereference per call (no vtable chase).
 * Function pointers are set by the derived class constructor (autogenerated).
 *
 * Run() is a plain device function (no coroutines). Task parallelism is
 * achieved by the caller via CDP child kernel launches.
 */
class Container {
 public:
  // ====================================================================
  // Function pointer types
  // ====================================================================

  /** Run a task method. Called from CDP child kernel. */
  using RunFn = void (*)(Container *, u32, hipc::FullPtr<Task>, RunContext &);

  /** Fix up task internal pointers after cudaMemcpy (SSO/SVO reseat).
   *  Called by RunTask before Run() for cpu2gpu POD-copied tasks. */
  using FixupTaskFn = void (*)(Container *, u32, hipc::FullPtr<Task>);

  /** Allocate a task struct for the given method */
  using AllocTaskFn = hipc::FullPtr<Task> (*)(Container *, u32);

  /** Allocate task and deserialize input in one dispatch */
  using AllocLoadDeserFn = hipc::FullPtr<Task> (*)(Container *, u32,
                                                    GpuLoadTaskArchive &);

  /** Allocate task and load deserialized data */
  using AllocLoadTaskFn = hipc::FullPtr<Task> (*)(Container *, u32,
                                                   GpuLoadTaskArchive &);

  /** Load (deserialize) task input from archive */
  using LoadTaskFn = void (*)(Container *, u32, GpuLoadTaskArchive &,
                               const hipc::FullPtr<Task> &);

  /** Save (serialize) task output to archive */
  using SaveTaskFn = void (*)(Container *, u32, GpuSaveTaskArchive &,
                               const hipc::FullPtr<Task> &);

  /** Destroy a task (call destructor) */
  using DestroyTaskFn = void (*)(Container *, u32, hipc::FullPtr<Task> &);

  // ====================================================================
  // Data members
  // ====================================================================
  PoolId pool_id_;
  u32 container_id_;

  // Inline function pointer table
  RunFn run_;
  FixupTaskFn fixup_task_;
  AllocTaskFn alloc_task_;
  AllocLoadDeserFn alloc_load_deser_;
  AllocLoadTaskFn alloc_load_task_;
  LoadTaskFn load_task_;
  SaveTaskFn save_task_;
  LoadTaskFn load_task_output_;
  DestroyTaskFn destroy_task_;

  /** Kernel-scope IpcManager pointer (Phase 10, SYCL only). The worker
   *  writes this from rctx.ipc_mgr_ before dispatching so autogen-emitted
   *  *Impl static methods (which don't receive rctx) can reach CHI_IPC
   *  via `self_->ipc_mgr_`. Placed after the function-pointer table so
   *  layout offsets to existing fields stay stable for code that depends
   *  on them. Always nullptr on CUDA/ROCm where __shared__ +
   *  GetBlockIpcManager handles per-block resolution. */
  IpcManager *ipc_mgr_ = nullptr;

  // ====================================================================
  // Constructor
  // ====================================================================
  HSHM_GPU_FUN Container()
      : container_id_(0),
        run_(nullptr), fixup_task_(nullptr),
        alloc_task_(nullptr), alloc_load_deser_(nullptr),
        alloc_load_task_(nullptr), load_task_(nullptr),
        save_task_(nullptr),
        load_task_output_(nullptr), destroy_task_(nullptr) {}
  ~Container() = default;

  /**
   * Initialize the GPU container
   * @param pool_id Pool identifier
   * @param container_id Container ID (typically node_id)
   */
  HSHM_GPU_FUN void Init(const PoolId &pool_id, u32 container_id) {
    pool_id_ = pool_id;
    container_id_ = container_id;
  }

  // ====================================================================
  // Dispatch methods (call through function pointers, single deref)
  // ====================================================================

  /**
   * Run a task method. Called from within a CDP child kernel.
   * @param method Method ID to dispatch
   * @param task_ptr Full pointer to the task
   * @param rctx Execution context
   */
  HSHM_GPU_FUN void Run(u32 method, hipc::FullPtr<Task> task_ptr,
                         RunContext &rctx) {
    run_(this, method, task_ptr, rctx);
  }

  /**
   * Fix up task internal pointers after cudaMemcpy (SSO/SVO reseat).
   * Called by RunTask before Run() for cpu2gpu POD-copied tasks.
   * No-op if fixup_task_ is null (task has no non-POD fields).
   */
  HSHM_GPU_FUN void FixupTask(u32 method, hipc::FullPtr<Task> task_ptr) {
    if (fixup_task_) fixup_task_(this, method, task_ptr);
  }

  /**
   * Allocate a task struct for the given method
   * @param method Method ID
   * @return Full pointer to the allocated task
   */
  HSHM_GPU_FUN hipc::FullPtr<Task> LocalAllocTask(u32 method) {
    return alloc_task_(this, method);
  }

  /**
   * Allocate task and deserialize input in one dispatch
   * @param method Method ID
   * @param archive Archive to deserialize from
   * @return Full pointer to the allocated task
   */
  HSHM_GPU_FUN hipc::FullPtr<Task> LocalAllocLoadDeser(
      u32 method, GpuLoadTaskArchive &archive) {
    return alloc_load_deser_(this, method, archive);
  }

  /**
   * Allocate task and load deserialized data
   * @param method Method ID
   * @param archive Archive to load from
   * @return Full pointer to the allocated task
   */
  HSHM_GPU_FUN hipc::FullPtr<Task> LocalAllocLoadTask(
      u32 method, GpuLoadTaskArchive &archive) {
    return alloc_load_task_(this, method, archive);
  }

  /**
   * Load (deserialize) task input from archive
   * @param method Method ID
   * @param archive Archive to load from
   * @param task Full pointer to the task
   */
  HSHM_GPU_FUN void LocalLoadTask(u32 method, GpuLoadTaskArchive &archive,
                                    const hipc::FullPtr<Task> &task) {
    load_task_(this, method, archive, task);
  }

  /**
   * Save (serialize) task output to archive
   * @param method Method ID
   * @param archive Archive to save to
   * @param task Full pointer to the task
   */
  HSHM_GPU_FUN void LocalSaveTask(u32 method, GpuSaveTaskArchive &archive,
                                    const hipc::FullPtr<Task> &task) {
    save_task_(this, method, archive, task);
  }

  /**
   * Load task output from archive
   * @param method Method ID
   * @param archive Archive to load from
   * @param task Full pointer to the task
   */
  HSHM_GPU_FUN void LocalLoadTaskOutput(u32 method,
                                          GpuLoadTaskArchive &archive,
                                          const hipc::FullPtr<Task> &task) {
    load_task_output_(this, method, archive, task);
  }

  /**
   * Destroy a task (call destructor)
   * @param method Method ID
   * @param task Full pointer to the task
   */
  HSHM_GPU_FUN void LocalDestroyTask(u32 method, hipc::FullPtr<Task> &task) {
    destroy_task_(this, method, task);
  }

  /**
   * Get remaining work for load balancing
   * @return Amount of work remaining (0 = idle)
   */
  HSHM_GPU_FUN u64 GetWorkRemaining() const { return 0; }
};

}  // namespace gpu
}  // namespace chi

#endif  // CHIMAERA_INCLUDE_CHIMAERA_GPU_CONTAINER_H_
