/**
 * Auto-generated execution implementation for safe_bdev ChiMod
 * Implements Container virtual APIs (Run, SaveTask, LoadTask, NewCopyTask,
 * NewTask) using switch-case dispatch.
 *
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "clio_runtime/safe_bdev/safe_bdev_runtime.h"
#include "clio_runtime/safe_bdev/autogen/safe_bdev_methods.h"
#include <clio_runtime/clio_runtime.h>
#include <clio_runtime/task.h>  // For TaskResume coroutine return type

namespace clio::run::safe_bdev {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Init(const chi::PoolId &pool_id, const std::string &pool_name,
                   chi::u32 container_id) {
  // Call base class initialization
  chi::Container::Init(pool_id, pool_name, container_id);

  // Initialize the client for this ChiMod
  client_ = Client(pool_id);

  // Initialize per-method load prediction model
  DefineModel(Method::kMaxMethodId);
  SetMethodNames(Method::GetMethodNames());
}

chi::TaskResume Runtime::Run(chi::u32 method,
                             ctp::ipc::FullPtr<chi::Task> task_ptr,
                             chi::RunContext &rctx) {
  CLIO_TASK_BODY_BEGIN
  switch (method) {
    case Method::kCreate: {
      ctp::ipc::FullPtr<CreateTask> typed_task =
          task_ptr.template Cast<CreateTask>();
      CLIO_CO_AWAIT(Create(typed_task, rctx));
      break;
    }
    case Method::kDestroy: {
      ctp::ipc::FullPtr<DestroyTask> typed_task =
          task_ptr.template Cast<DestroyTask>();
      CLIO_CO_AWAIT(Destroy(typed_task, rctx));
      break;
    }
    case Method::kMonitor: {
      ctp::ipc::FullPtr<MonitorTask> typed_task =
          task_ptr.template Cast<MonitorTask>();
      CLIO_CO_AWAIT(Monitor(typed_task, rctx));
      break;
    }
    case Method::kAllocateBlocks: {
      ctp::ipc::FullPtr<AllocateBlocksTask> typed_task =
          task_ptr.template Cast<AllocateBlocksTask>();
      CLIO_CO_AWAIT(AllocateBlocks(typed_task, rctx));
      break;
    }
    case Method::kFreeBlocks: {
      ctp::ipc::FullPtr<FreeBlocksTask> typed_task =
          task_ptr.template Cast<FreeBlocksTask>();
      CLIO_CO_AWAIT(FreeBlocks(typed_task, rctx));
      break;
    }
    case Method::kWrite: {
      ctp::ipc::FullPtr<WriteTask> typed_task =
          task_ptr.template Cast<WriteTask>();
      CLIO_CO_AWAIT(Write(typed_task, rctx));
      break;
    }
    case Method::kRead: {
      ctp::ipc::FullPtr<ReadTask> typed_task =
          task_ptr.template Cast<ReadTask>();
      CLIO_CO_AWAIT(Read(typed_task, rctx));
      break;
    }
    case Method::kGetStats: {
      ctp::ipc::FullPtr<GetStatsTask> typed_task =
          task_ptr.template Cast<GetStatsTask>();
      CLIO_CO_AWAIT(GetStats(typed_task, rctx));
      break;
    }
    case Method::kAddBdev: {
      ctp::ipc::FullPtr<AddBdevTask> typed_task =
          task_ptr.template Cast<AddBdevTask>();
      CLIO_CO_AWAIT(AddBdev(typed_task, rctx));
      break;
    }
    case Method::kRemoveBdev: {
      ctp::ipc::FullPtr<RemoveBdevTask> typed_task =
          task_ptr.template Cast<RemoveBdevTask>();
      CLIO_CO_AWAIT(RemoveBdev(typed_task, rctx));
      break;
    }
    case Method::kRecoverBdev: {
      ctp::ipc::FullPtr<RecoverBdevTask> typed_task =
          task_ptr.template Cast<RecoverBdevTask>();
      CLIO_CO_AWAIT(RecoverBdev(typed_task, rctx));
      break;
    }
    case Method::kBuildParity: {
      ctp::ipc::FullPtr<BuildParityTask> typed_task =
          task_ptr.template Cast<BuildParityTask>();
      CLIO_CO_AWAIT(BuildParity(typed_task, rctx));
      break;
    }
    case Method::kFlushAllocLog: {
      ctp::ipc::FullPtr<FlushAllocLogTask> typed_task =
          task_ptr.template Cast<FlushAllocLogTask>();
      CLIO_CO_AWAIT(FlushAllocLog(typed_task, rctx));
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
  CLIO_CO_RETURN;
  CLIO_TASK_BODY_END
}

void Runtime::SaveTask(chi::u32 method, chi::SaveTaskArchive &archive,
                       ctp::ipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kAllocateBlocks: {
      auto typed_task = task_ptr.template Cast<AllocateBlocksTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kFreeBlocks: {
      auto typed_task = task_ptr.template Cast<FreeBlocksTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kWrite: {
      auto typed_task = task_ptr.template Cast<WriteTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kRead: {
      auto typed_task = task_ptr.template Cast<ReadTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetStats: {
      auto typed_task = task_ptr.template Cast<GetStatsTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kAddBdev: {
      auto typed_task = task_ptr.template Cast<AddBdevTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kRemoveBdev: {
      auto typed_task = task_ptr.template Cast<RemoveBdevTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kRecoverBdev: {
      auto typed_task = task_ptr.template Cast<RecoverBdevTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kBuildParity: {
      auto typed_task = task_ptr.template Cast<BuildParityTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kFlushAllocLog: {
      auto typed_task = task_ptr.template Cast<FlushAllocLogTask>();
      archive << *typed_task.ptr_;
      break;
    }
    default: {
      break;
    }
  }
}

void Runtime::LoadTask(chi::u32 method, chi::LoadTaskArchive &archive,
                       ctp::ipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kAllocateBlocks: {
      auto typed_task = task_ptr.template Cast<AllocateBlocksTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kFreeBlocks: {
      auto typed_task = task_ptr.template Cast<FreeBlocksTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kWrite: {
      auto typed_task = task_ptr.template Cast<WriteTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kRead: {
      auto typed_task = task_ptr.template Cast<ReadTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetStats: {
      auto typed_task = task_ptr.template Cast<GetStatsTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kAddBdev: {
      auto typed_task = task_ptr.template Cast<AddBdevTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kRemoveBdev: {
      auto typed_task = task_ptr.template Cast<RemoveBdevTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kRecoverBdev: {
      auto typed_task = task_ptr.template Cast<RecoverBdevTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kBuildParity: {
      auto typed_task = task_ptr.template Cast<BuildParityTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kFlushAllocLog: {
      auto typed_task = task_ptr.template Cast<FlushAllocLogTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    default: {
      break;
    }
  }
}

ctp::ipc::FullPtr<chi::Task> Runtime::AllocLoadTask(
    chi::u32 method, chi::LoadTaskArchive &archive) {
  ctp::ipc::FullPtr<chi::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalLoadTask(chi::u32 method, chi::DefaultLoadArchive &archive,
                            ctp::ipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kAllocateBlocks: {
      auto typed_task = task_ptr.template Cast<AllocateBlocksTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kFreeBlocks: {
      auto typed_task = task_ptr.template Cast<FreeBlocksTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kWrite: {
      auto typed_task = task_ptr.template Cast<WriteTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kRead: {
      auto typed_task = task_ptr.template Cast<ReadTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetStats: {
      auto typed_task = task_ptr.template Cast<GetStatsTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kAddBdev: {
      auto typed_task = task_ptr.template Cast<AddBdevTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kRemoveBdev: {
      auto typed_task = task_ptr.template Cast<RemoveBdevTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kRecoverBdev: {
      auto typed_task = task_ptr.template Cast<RecoverBdevTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kBuildParity: {
      auto typed_task = task_ptr.template Cast<BuildParityTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kFlushAllocLog: {
      auto typed_task = task_ptr.template Cast<FlushAllocLogTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    default: {
      break;
    }
  }
}

ctp::ipc::FullPtr<chi::Task> Runtime::LocalAllocLoadTask(
    chi::u32 method, chi::DefaultLoadArchive &archive) {
  ctp::ipc::FullPtr<chi::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LocalLoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalSaveTask(chi::u32 method, chi::DefaultSaveArchive &archive,
                            ctp::ipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kAllocateBlocks: {
      auto typed_task = task_ptr.template Cast<AllocateBlocksTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kFreeBlocks: {
      auto typed_task = task_ptr.template Cast<FreeBlocksTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kWrite: {
      auto typed_task = task_ptr.template Cast<WriteTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kRead: {
      auto typed_task = task_ptr.template Cast<ReadTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetStats: {
      auto typed_task = task_ptr.template Cast<GetStatsTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kAddBdev: {
      auto typed_task = task_ptr.template Cast<AddBdevTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kRemoveBdev: {
      auto typed_task = task_ptr.template Cast<RemoveBdevTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kRecoverBdev: {
      auto typed_task = task_ptr.template Cast<RecoverBdevTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kBuildParity: {
      auto typed_task = task_ptr.template Cast<BuildParityTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kFlushAllocLog: {
      auto typed_task = task_ptr.template Cast<FlushAllocLogTask>();
      archive << *typed_task.ptr_;
      break;
    }
    default: {
      break;
    }
  }
}

ctp::ipc::FullPtr<chi::Task> Runtime::NewCopyTask(
    chi::u32 method, ctp::ipc::FullPtr<chi::Task> orig_task_ptr, bool deep) {
  auto *ipc_manager = CLIO_IPC;
  if (!ipc_manager) {
    return ctp::ipc::FullPtr<chi::Task>();
  }

  switch (method) {
    case Method::kCreate: {
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<CreateTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDestroy: {
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<DestroyTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kMonitor: {
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<MonitorTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kAllocateBlocks: {
      auto new_task_ptr = ipc_manager->NewTask<AllocateBlocksTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<AllocateBlocksTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kFreeBlocks: {
      auto new_task_ptr = ipc_manager->NewTask<FreeBlocksTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<FreeBlocksTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kWrite: {
      auto new_task_ptr = ipc_manager->NewTask<WriteTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<WriteTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kRead: {
      auto new_task_ptr = ipc_manager->NewTask<ReadTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<ReadTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetStats: {
      auto new_task_ptr = ipc_manager->NewTask<GetStatsTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<GetStatsTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kAddBdev: {
      auto new_task_ptr = ipc_manager->NewTask<AddBdevTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<AddBdevTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kRemoveBdev: {
      auto new_task_ptr = ipc_manager->NewTask<RemoveBdevTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<RemoveBdevTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kRecoverBdev: {
      auto new_task_ptr = ipc_manager->NewTask<RecoverBdevTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<RecoverBdevTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kBuildParity: {
      auto new_task_ptr = ipc_manager->NewTask<BuildParityTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<BuildParityTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kFlushAllocLog: {
      auto new_task_ptr = ipc_manager->NewTask<FlushAllocLogTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<FlushAllocLogTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    default: {
      auto new_task_ptr = ipc_manager->NewTask<chi::Task>();
      if (!new_task_ptr.IsNull()) {
        new_task_ptr->Copy(orig_task_ptr);
        return new_task_ptr;
      }
      break;
    }
  }

  (void)deep;  // Deep copy parameter reserved for future use
  return ctp::ipc::FullPtr<chi::Task>();
}

ctp::ipc::FullPtr<chi::Task> Runtime::NewTask(chi::u32 method) {
  auto *ipc_manager = CLIO_IPC;
  if (!ipc_manager) {
    return ctp::ipc::FullPtr<chi::Task>();
  }

  switch (method) {
    case Method::kCreate: {
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kDestroy: {
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kMonitor: {
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kAllocateBlocks: {
      auto new_task_ptr = ipc_manager->NewTask<AllocateBlocksTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kFreeBlocks: {
      auto new_task_ptr = ipc_manager->NewTask<FreeBlocksTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kWrite: {
      auto new_task_ptr = ipc_manager->NewTask<WriteTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kRead: {
      auto new_task_ptr = ipc_manager->NewTask<ReadTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kGetStats: {
      auto new_task_ptr = ipc_manager->NewTask<GetStatsTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kAddBdev: {
      auto new_task_ptr = ipc_manager->NewTask<AddBdevTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kRemoveBdev: {
      auto new_task_ptr = ipc_manager->NewTask<RemoveBdevTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kRecoverBdev: {
      auto new_task_ptr = ipc_manager->NewTask<RecoverBdevTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kBuildParity: {
      auto new_task_ptr = ipc_manager->NewTask<BuildParityTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kFlushAllocLog: {
      auto new_task_ptr = ipc_manager->NewTask<FlushAllocLogTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    default: {
      return ctp::ipc::FullPtr<chi::Task>();
    }
  }
}

void Runtime::Aggregate(chi::u32 method, ctp::ipc::FullPtr<chi::Task> orig_task,
                        const ctp::ipc::FullPtr<chi::Task> &replica_task) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = orig_task.template Cast<CreateTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = orig_task.template Cast<DestroyTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kMonitor: {
      auto typed_task = orig_task.template Cast<MonitorTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kAllocateBlocks: {
      auto typed_task = orig_task.template Cast<AllocateBlocksTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kFreeBlocks: {
      auto typed_task = orig_task.template Cast<FreeBlocksTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kWrite: {
      auto typed_task = orig_task.template Cast<WriteTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kRead: {
      auto typed_task = orig_task.template Cast<ReadTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kGetStats: {
      auto typed_task = orig_task.template Cast<GetStatsTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kAddBdev: {
      auto typed_task = orig_task.template Cast<AddBdevTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kRemoveBdev: {
      auto typed_task = orig_task.template Cast<RemoveBdevTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kRecoverBdev: {
      auto typed_task = orig_task.template Cast<RecoverBdevTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kBuildParity: {
      auto typed_task = orig_task.template Cast<BuildParityTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kFlushAllocLog: {
      auto typed_task = orig_task.template Cast<FlushAllocLogTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    default: {
      orig_task->Aggregate(replica_task);
      break;
    }
  }
}

void Runtime::DelTask(chi::u32 method, ctp::ipc::FullPtr<chi::Task> task_ptr) {
  auto *ipc_manager = CLIO_IPC;
  if (!ipc_manager) return;
  switch (method) {
    case Method::kCreate: {
      ipc_manager->DelTask(task_ptr.template Cast<CreateTask>());
      break;
    }
    case Method::kDestroy: {
      ipc_manager->DelTask(task_ptr.template Cast<DestroyTask>());
      break;
    }
    case Method::kMonitor: {
      ipc_manager->DelTask(task_ptr.template Cast<MonitorTask>());
      break;
    }
    case Method::kAllocateBlocks: {
      ipc_manager->DelTask(task_ptr.template Cast<AllocateBlocksTask>());
      break;
    }
    case Method::kFreeBlocks: {
      ipc_manager->DelTask(task_ptr.template Cast<FreeBlocksTask>());
      break;
    }
    case Method::kWrite: {
      ipc_manager->DelTask(task_ptr.template Cast<WriteTask>());
      break;
    }
    case Method::kRead: {
      ipc_manager->DelTask(task_ptr.template Cast<ReadTask>());
      break;
    }
    case Method::kGetStats: {
      ipc_manager->DelTask(task_ptr.template Cast<GetStatsTask>());
      break;
    }
    case Method::kAddBdev: {
      ipc_manager->DelTask(task_ptr.template Cast<AddBdevTask>());
      break;
    }
    case Method::kRemoveBdev: {
      ipc_manager->DelTask(task_ptr.template Cast<RemoveBdevTask>());
      break;
    }
    case Method::kRecoverBdev: {
      ipc_manager->DelTask(task_ptr.template Cast<RecoverBdevTask>());
      break;
    }
    case Method::kBuildParity: {
      ipc_manager->DelTask(task_ptr.template Cast<BuildParityTask>());
      break;
    }
    case Method::kFlushAllocLog: {
      ipc_manager->DelTask(task_ptr.template Cast<FlushAllocLogTask>());
      break;
    }
    default: {
      ipc_manager->DelTask(task_ptr);
      break;
    }
  }
}

}  // namespace clio::run::safe_bdev
