// Auto-generated GPU lib_exec for MOD_NAME
// Include inside GpuRuntime class body
// This file is autogenerated - do not edit manually.

template <typename ArchiveT>
HSHM_GPU_FUN void LoadTaskTmpl(
    chi::u32 method, ArchiveT &archive,
    const hipc::FullPtr<chi::Task> &task) {
  switch (method) {
    case Method::kGpuSubmit: {
      auto typed = task.template Cast<GpuSubmitTask>();
      if (archive.GetMsgType() == chi::LocalMsgType::kSerializeIn)
        typed->SerializeIn(archive);
      else
        typed->SerializeOut(archive);
      break;
    }
    case Method::kSubtaskTest: {
      auto typed = task.template Cast<SubtaskTestTask>();
      if (archive.GetMsgType() == chi::LocalMsgType::kSerializeIn)
        typed->SerializeIn(archive);
      else
        typed->SerializeOut(archive);
      break;
    }
    default: break;
  }
}

template <typename ArchiveT>
HSHM_GPU_FUN void SaveTaskTmpl(
    chi::u32 method, ArchiveT &archive,
    const hipc::FullPtr<chi::Task> &task) {
  switch (method) {
    case Method::kGpuSubmit:
      task.template Cast<GpuSubmitTask>()->SerializeOut(archive);
      break;
    case Method::kSubtaskTest:
      task.template Cast<SubtaskTestTask>()->SerializeOut(archive);
      break;
    default: break;
  }
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN void RunImpl(
    chi::gpu::Container *self_, chi::u32 method,
    hipc::FullPtr<chi::Task> task_ptr, chi::gpu::RunContext &rctx) {
  auto *self = static_cast<GpuRuntime *>(self_);
  switch (method) {
    case Method::kGpuSubmit:
      self->GpuSubmit(task_ptr.template Cast<GpuSubmitTask>(), rctx);
      break;
    case Method::kSubtaskTest:
      self->SubtaskTest(task_ptr.template Cast<SubtaskTestTask>(), rctx);
      break;
    default: break;
  }
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN hipc::FullPtr<chi::Task> AllocTaskImpl(
    chi::gpu::Container *self_, chi::u32 method) {
  // Phase 10: bind g_ipc_manager_ptr so CHI_IPC under SYCL resolves
  // to the kernel-scope IpcManager (set by the worker via
  // container->ipc_mgr_ before dispatch).
  [[maybe_unused]] auto *g_ipc_manager_ptr = self_->ipc_mgr_;
  switch (method) {
    case Method::kGpuSubmit: {
      auto _tp = CHI_IPC->NewTaskBase<GpuSubmitTask>(0); return _tp.template Cast<chi::Task>();
    }
    case Method::kSubtaskTest: {
      auto _tp = CHI_IPC->NewTaskBase<SubtaskTestTask>(0); return _tp.template Cast<chi::Task>();
    }
    default: return hipc::FullPtr<chi::Task>::GetNull();
  }
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN hipc::FullPtr<chi::Task> AllocLoadTaskDefaultImpl(
    chi::gpu::Container *self_, chi::u32 method, chi::GpuLoadTaskArchive &ar) {
  auto *self = static_cast<GpuRuntime *>(self_);
  auto task_ptr = self->alloc_task_(self_, method);
  if (task_ptr.IsNull()) return task_ptr;
  ar.SetMsgType(chi::LocalMsgType::kSerializeIn);
  self->LoadTaskTmpl(method, ar, task_ptr);
  return task_ptr;
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN hipc::FullPtr<chi::Task> AllocLoadDeserImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::GpuLoadTaskArchive &ar) {
  auto *self = static_cast<GpuRuntime *>(self_);
  auto task_ptr = AllocTaskImpl(self_, method);
  if (!task_ptr.IsNull()) {
    ar.SetMsgType(chi::LocalMsgType::kSerializeIn);
    self->LoadTaskTmpl(method, ar, task_ptr);
  }
  return task_ptr;
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN void LoadTaskDefaultImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::GpuLoadTaskArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  ar.SetMsgType(chi::LocalMsgType::kSerializeIn);
  static_cast<GpuRuntime *>(self_)->LoadTaskTmpl(method, ar, task);
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN void SaveTaskDefaultImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::GpuSaveTaskArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  static_cast<GpuRuntime *>(self_)->SaveTaskTmpl(method, ar, task);
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN void LoadTaskOutputImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::GpuLoadTaskArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  ar.SetMsgType(chi::LocalMsgType::kSerializeOut);
  static_cast<GpuRuntime *>(self_)->LoadTaskTmpl(method, ar, task);
}

HSHM_INDIRECTLY_CALLABLE static HSHM_GPU_FUN void DestroyTaskImpl(
    chi::gpu::Container *self_, chi::u32 method,
    hipc::FullPtr<chi::Task> &task) {
  if (task.IsNull()) return;
  switch (method) {
    case Method::kGpuSubmit:
      task.template Cast<GpuSubmitTask>().ptr_->~GpuSubmitTask();
      break;
    case Method::kSubtaskTest:
      task.template Cast<SubtaskTestTask>().ptr_->~SubtaskTestTask();
      break;
    default: task.ptr_->~Task(); break;
  }
}

HSHM_GPU_FUN GpuRuntime() {
  run_ = &RunImpl;
  fixup_task_ = nullptr;  // GpuSubmitTask, SubtaskTestTask are fully POD
  alloc_task_ = &AllocTaskImpl;
  alloc_load_deser_ = &AllocLoadDeserImpl;
  alloc_load_task_ = &AllocLoadTaskDefaultImpl;
  load_task_ = &LoadTaskDefaultImpl;
  save_task_ = &SaveTaskDefaultImpl;
  load_task_output_ = &LoadTaskOutputImpl;
  destroy_task_ = &DestroyTaskImpl;
}
